import React, { useMemo, useState } from 'react';
import { Download, Edit3, Plus, Search } from 'lucide-react';
import { Badge } from '../../../../components/ui/Badge';
import { Button } from '../../../../components/ui/Button';
import { Card } from '../../../../components/ui/Card';
import { Modal } from '../../../../components/ui/Modal';
import {
  DEFAULT_DUTY_TYPES,
  DUTY_TYPES_STORAGE_KEY,
  DutyTypeRecord,
  createTeacherRecordId,
  downloadTeacherCsv,
  loadTeacherCollection,
  saveTeacherCollection
} from './teacherData';

const dutyCategories = ['Campus Safety', 'Academic', 'Examination', 'Transport', 'Events', 'Hostel', 'Sports', 'Safety', 'Campus', 'Health'];
const frequencies = ['Daily', 'Weekly', 'Per Exam', 'Per Event', 'As Needed', 'Rotational', 'Per PTM', 'Per Period', 'On-call'];
const inputClass = 'w-full rounded-lg border border-slate-300 bg-white px-3 py-2 text-sm text-slate-800 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100';
const labelClass = 'mb-1 block text-xs font-semibold text-slate-600';
function Field({ label, hint, children }: { label: string; hint?: string; children: React.ReactNode }) { return <label className="block"><span className={labelClass}>{label}</span>{children}{hint && <span className="mt-1 block text-[11px] text-slate-500">{hint}</span>}</label>; }
function Panel({ title, children }: { title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-slate-200 bg-white"><h3 className="border-b border-slate-100 bg-slate-50 px-4 py-3 text-sm font-bold text-slate-800">{title}</h3><div className="space-y-4 p-4">{children}</div></section>; }
const codeForName = (name: string) => `DUTY-${name.trim().toUpperCase().replace(/[^A-Z0-9]+/g, '-').replace(/^-|-$/g, '') || 'NEW-DUTY'}`;
const newDuty = (): DutyTypeRecord => ({
  id: createTeacherRecordId('duty'), name: '', code: 'DUTY-NEW-DUTY', icon: '📋', category: 'Academic', description: '', frequency: 'Daily', startTime: '07:00 AM', endTime: '08:00 AM', defaultLocation: '', advanceNoticeDays: 1, teachersPerDuty: 1, eligibleAllTeachingStaff: true, specificDesignation: '', rotationMethod: 'Automatic rotation', canBeSwapped: true, canBeExcused: true, minimumGapDays: 2, responsibilities: [], requiredAttire: 'Formal school uniform', reportingTo: 'Vice Principal on duty', actionOnAbsence: 'Log as duty absent — impacts appraisal', trackAttendance: true, attendanceMethod: 'Supervisor', affectPayroll: false, affectAppraisal: true, status: 'Active'
});

export function DutyMaster() {
  const [duties, setDuties] = useState<DutyTypeRecord[]>(() => loadTeacherCollection(DUTY_TYPES_STORAGE_KEY, DEFAULT_DUTY_TYPES));
  const [search, setSearch] = useState('');
  const [categoryFilter, setCategoryFilter] = useState('All');
  const [form, setForm] = useState<DutyTypeRecord | null>(null);
  const [message, setMessage] = useState('');
  const filtered = useMemo(() => duties.filter((duty) => {
    const term = search.trim().toLowerCase();
    return (!term || `${duty.name} ${duty.code} ${duty.category} ${duty.frequency}`.toLowerCase().includes(term)) && (categoryFilter === 'All' || duty.category === categoryFilter);
  }), [duties, search, categoryFilter]);
  const persist = (next: DutyTypeRecord[]) => { setDuties(next); saveTeacherCollection(DUTY_TYPES_STORAGE_KEY, next); };
  const update = <K extends keyof DutyTypeRecord,>(key: K, value: DutyTypeRecord[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const save = () => {
    if (!form?.name.trim()) { setMessage('Enter a duty type name before saving.'); return; }
    const saved: DutyTypeRecord = { ...form, name: form.name.trim(), code: codeForName(form.name), teachersPerDuty: Math.max(1, Number(form.teachersPerDuty)), minimumGapDays: Math.max(0, Number(form.minimumGapDays)), responsibilities: form.responsibilities.filter(Boolean) };
    persist(duties.some((item) => item.id === saved.id) ? duties.map((item) => item.id === saved.id ? saved : item) : [saved, ...duties]);
    setForm(null); setMessage(`“${saved.name}” saved to Duty Master.`); window.setTimeout(() => setMessage(''), 3500);
  };
  const exportDuties = () => downloadTeacherCsv('duty-types.csv', filtered.map((duty) => ({ Name: duty.name, Code: duty.code, Category: duty.category, Frequency: duty.frequency, Status: duty.status })));
  const toggleStatus = (duty: DutyTypeRecord) => persist(duties.map((item) => item.id === duty.id ? { ...item, status: item.status === 'Active' ? 'Inactive' : 'Active' } : item));

  return <div className="space-y-6 p-4 md:p-6">
    <div className="flex flex-col gap-4 md:flex-row md:items-start md:justify-between"><div><p className="text-xs font-semibold uppercase tracking-widest text-indigo-600">Teacher Duties Section</p><h1 className="mt-1 text-2xl font-bold text-slate-900">📋 Duty Types Master</h1><p className="mt-1 text-sm text-slate-500">Define recurring duty templates, assignment rules, responsibilities and attendance settings.</p></div><div className="flex gap-2"><Button variant="outline" leftIcon={<Download className="h-4 w-4" />} onClick={exportDuties}>Export</Button><Button leftIcon={<Plus className="h-4 w-4" />} onClick={() => setForm(newDuty())}>Add Duty Type</Button></div></div>
    {message && <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm text-indigo-800">{message}</div>}
    <Card noPadding className="overflow-hidden"><div className="flex flex-col gap-3 border-b border-slate-100 bg-slate-50 p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input className={`${inputClass} pl-9`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search duty names or codes..." /></div><select className={`${inputClass} md:w-56`} value={categoryFilter} onChange={(event) => setCategoryFilter(event.target.value)}><option>All</option>{dutyCategories.map((category) => <option key={category}>{category}</option>)}</select><span className="self-center text-xs text-slate-500">{filtered.length} of {duties.length} duty types</span></div><div className="overflow-x-auto"><table className="w-full min-w-[850px] text-left text-sm"><thead className="text-[11px] uppercase tracking-wide text-slate-500"><tr><th className="px-4 py-3">#</th><th className="px-4 py-3">Duty Type Name</th><th className="px-4 py-3">Category</th><th className="px-4 py-3">Frequency</th><th className="px-4 py-3">Status</th><th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((duty, index) => <tr key={duty.id} className="hover:bg-indigo-50/30"><td className="px-4 py-3 text-slate-400">{index + 1}</td><td className="px-4 py-3"><span className="mr-2 text-lg">{duty.icon}</span><span className="font-semibold">{duty.name}</span><div className="ml-8 font-mono text-[10px] text-slate-400">{duty.code}</div></td><td className="px-4 py-3"><Badge variant="info">{duty.category}</Badge></td><td className="px-4 py-3">{duty.frequency}</td><td className="px-4 py-3"><Badge variant={duty.status === 'Active' ? 'success' : 'default'}>{duty.status}</Badge></td><td className="px-4 py-3 text-right"><button className="rounded p-2 text-slate-500 hover:bg-indigo-50 hover:text-indigo-700" onClick={() => setForm({ ...duty, responsibilities: [...duty.responsibilities] })}><Edit3 className="h-4 w-4" /></button><button className="rounded px-2 py-1 text-[11px] text-slate-500 hover:bg-slate-100" onClick={() => toggleStatus(duty)}>{duty.status === 'Active' ? 'Deactivate' : 'Activate'}</button></td></tr>)}{filtered.length === 0 && <tr><td colSpan={6} className="px-4 py-10 text-center text-sm text-slate-400">No duty types match these filters.</td></tr>}</tbody></table></div></Card>
    <Modal isOpen={Boolean(form)} onClose={() => setForm(null)} title={form ? `${duties.some((item) => item.id === form.id) ? 'Edit' : 'Create'} Duty Type — ${form.name || 'New Duty'}` : 'Duty Type'} size="xl" footer={<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setForm(null)}>Cancel</Button><Button onClick={save}>Save Duty Type</Button></div>}>
      {form && <div className="max-h-[76vh] space-y-4 overflow-y-auto pr-1">
        <Panel title="Panel 1 · Duty Identity"><div className="grid gap-4 md:grid-cols-2"><Field label="Duty Name"><input className={inputClass} value={form.name} onChange={(event) => setForm((current) => current ? { ...current, name: event.target.value, code: codeForName(event.target.value) } : current)} placeholder="Gate Duty — Morning" /></Field><Field label="Duty Code — Auto-generated"><input className={`${inputClass} bg-slate-50 font-mono`} readOnly value={form.code} /></Field><Field label="Icon / Emoji"><input className={inputClass} value={form.icon} onChange={(event) => update('icon', event.target.value)} /></Field><Field label="Category"><select className={inputClass} value={form.category} onChange={(event) => update('category', event.target.value)}>{dutyCategories.map((category) => <option key={category}>{category}</option>)}</select></Field><Field label="Status"><select className={inputClass} value={form.status} onChange={(event) => update('status', event.target.value as DutyTypeRecord['status'])}><option>Active</option><option>Inactive</option></select></Field><Field label="Description"><textarea className={`${inputClass} min-h-20`} value={form.description} onChange={(event) => update('description', event.target.value)} placeholder="Purpose and scope of this duty" /></Field></div></Panel>
        <Panel title="Panel 2 · Duty Schedule Defaults"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Field label="Frequency"><select className={inputClass} value={form.frequency} onChange={(event) => update('frequency', event.target.value)}>{frequencies.map((frequency) => <option key={frequency}>{frequency}</option>)}</select></Field><Field label="Default Start Time"><input className={inputClass} value={form.startTime} onChange={(event) => update('startTime', event.target.value)} /></Field><Field label="Default End Time"><input className={inputClass} value={form.endTime} onChange={(event) => update('endTime', event.target.value)} /></Field><Field label="Default Location"><input className={inputClass} value={form.defaultLocation} onChange={(event) => update('defaultLocation', event.target.value)} /></Field><Field label="Advance Notice"><input type="number" min="0" className={inputClass} value={form.advanceNoticeDays} onChange={(event) => update('advanceNoticeDays', Number(event.target.value))} /></Field></div></Panel>
        <Panel title="Panel 3 · Assignment Rules"><div className="grid gap-4 md:grid-cols-2 xl:grid-cols-3"><Field label="Teachers per Duty"><input type="number" min="1" className={inputClass} value={form.teachersPerDuty} onChange={(event) => update('teachersPerDuty', Number(event.target.value))} /></Field><Field label="Eligible Staff"><select className={inputClass} value={form.eligibleAllTeachingStaff ? 'All teaching staff' : 'Specific designation'} onChange={(event) => update('eligibleAllTeachingStaff', event.target.value === 'All teaching staff')}><option>All teaching staff</option><option>Specific designation</option></select></Field>{!form.eligibleAllTeachingStaff && <Field label="Specific Designation"><input className={inputClass} value={form.specificDesignation} onChange={(event) => update('specificDesignation', event.target.value)} placeholder="e.g. PGT / PET" /></Field>}<Field label="Rotation Method"><select className={inputClass} value={form.rotationMethod} onChange={(event) => update('rotationMethod', event.target.value as DutyTypeRecord['rotationMethod'])}><option>Automatic rotation</option><option>Manual assignment</option></select></Field><Field label="Minimum Gap Between Duties"><input type="number" min="0" className={inputClass} value={form.minimumGapDays} onChange={(event) => update('minimumGapDays', Number(event.target.value))} /></Field></div><div className="grid gap-2 md:grid-cols-3"><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.canBeSwapped} onChange={(event) => update('canBeSwapped', event.target.checked)} />Duty can be swapped with consent</label><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.canBeExcused} onChange={(event) => update('canBeExcused', event.target.checked)} />May be excused with valid reason</label><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.rotationMethod === 'Automatic rotation'} onChange={(event) => update('rotationMethod', event.target.checked ? 'Automatic rotation' : 'Manual assignment')} />Automatic rotation enabled</label></div></Panel>
        <Panel title="Panel 4 · Rules & Responsibilities"><Field label="Responsibilities" hint="One responsibility per line."><textarea className={`${inputClass} min-h-28`} value={form.responsibilities.join('\n')} onChange={(event) => update('responsibilities', event.target.value.split('\n').filter(Boolean))} placeholder={'Be present at assigned location on time\nSupervise students and report incidents'} /></Field><div className="grid gap-4 md:grid-cols-3"><Field label="Required Attire"><input className={inputClass} value={form.requiredAttire} onChange={(event) => update('requiredAttire', event.target.value)} /></Field><Field label="Reporting To"><input className={inputClass} value={form.reportingTo} onChange={(event) => update('reportingTo', event.target.value)} /></Field><Field label="Action on Absence"><input className={inputClass} value={form.actionOnAbsence} onChange={(event) => update('actionOnAbsence', event.target.value)} /></Field></div></Panel>
        <Panel title="Panel 5 · Tracking Settings"><div className="grid gap-3 md:grid-cols-2"><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.trackAttendance} onChange={(event) => update('trackAttendance', event.target.checked)} />Track attendance for this duty</label><Field label="How to Mark Attendance"><select className={inputClass} value={form.attendanceMethod} onChange={(event) => update('attendanceMethod', event.target.value as DutyTypeRecord['attendanceMethod'])}><option>Supervisor</option><option>Teacher self-mark</option><option>Biometric</option></select></Field><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.affectPayroll} onChange={(event) => update('affectPayroll', event.target.checked)} />Affect payroll for duty absence</label><label className="flex items-center gap-2 rounded-lg border border-slate-100 p-3 text-xs"><input type="checkbox" checked={form.affectAppraisal} onChange={(event) => update('affectAppraisal', event.target.checked)} />Include duty performance in annual appraisal</label></div></Panel>
      </div>}
    </Modal>
  </div>;
}
