import React, { useMemo, useRef, useState } from 'react';
import { Download, Plus, Printer, Search, Upload } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Modal } from '../../../components/ui/Modal';
import { ACADEMIC_PLANNING_KEYS, ACADEMIC_YEARS, BLOOM_LEVELS, CLASSES, DEFAULT_CURRICULUM_CHAPTERS, DEFAULT_LEARNING_OBJECTIVES, SUBJECTS, createBlankObjective, downloadPlanningCsv, loadPlanningCollection, newPlanningId, savePlanningCollection, type CurriculumChapter, type LearningObjectiveRecord } from './academicPlanningData';
import { EmptyState, PageHeader, PlanningPanel, SelectField, StatusPill, TextAreaField, TextField } from './academicPlanningData.ts';

interface SubjectOutcomeRecord { id: string; className: string; subject: string; academicYear: string; statement: string; boardObjectives: string; nepFramework: string; }
const DEFAULT_SUBJECT_OUTCOMES: SubjectOutcomeRecord[] = [
  { id: 'out-1', className: 'Class 10', subject: 'Science', academicYear: '2025-26', statement: 'Apply the scientific method to everyday observations.\nUnderstand the interdependence of physics, chemistry and biology.\nConnect textbook concepts to real-world applications.\nSolve numerical problems in physics and chemistry.\nDevelop environmental awareness and sustainability thinking.', boardObjectives: 'CBSE competency-based learning outcomes; scientific inquiry and application.', nepFramework: 'Critical thinking, scientific temper, communication and experiential learning.' },
  { id: 'out-2', className: 'Class 10', subject: 'Mathematics', academicYear: '2025-26', statement: 'Learners reason mathematically, solve multi-step problems and communicate solutions using appropriate representations.', boardObjectives: 'CBSE mathematics learning outcomes and competency-based assessment.', nepFramework: 'Problem solving, logical reasoning and quantitative literacy.' }
];
const competencies = ['Critical Thinking', 'Communication', 'Creativity', 'Collaboration', 'Scientific Inquiry', 'Digital Literacy', 'Citizenship', 'Problem Solving', 'Environmental Awareness'];
const objectivesInput = 'w-full rounded-lg border border-slate-300 px-3 py-2 text-sm focus:border-indigo-500 focus:outline-none';

export function LearningObjectivesMaster() {
  const [records, setRecords] = useState<LearningObjectiveRecord[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.objectives, DEFAULT_LEARNING_OBJECTIVES));
  const [chapters] = useState<CurriculumChapter[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.chapters, DEFAULT_CURRICULUM_CHAPTERS));
  const [outcomes, setOutcomes] = useState<SubjectOutcomeRecord[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.subjectOutcomes, DEFAULT_SUBJECT_OUTCOMES));
  const [selectedClass, setSelectedClass] = useState('Class 10');
  const [selectedSubject, setSelectedSubject] = useState('Science');
  const [selectedChapter, setSelectedChapter] = useState('All Chapters');
  const [bloomFilter, setBloomFilter] = useState('All Levels');
  const [view, setView] = useState('By Chapter');
  const [search, setSearch] = useState('');
  const [form, setForm] = useState<LearningObjectiveRecord | null>(null);
  const [outcomeForm, setOutcomeForm] = useState<SubjectOutcomeRecord | null>(null);
  const [message, setMessage] = useState('');
  const importRef = useRef<HTMLInputElement>(null);
  const persist = (next: LearningObjectiveRecord[]) => { setRecords(next); savePlanningCollection(ACADEMIC_PLANNING_KEYS.objectives, next); };
  const persistOutcomes = (next: SubjectOutcomeRecord[]) => { setOutcomes(next); savePlanningCollection(ACADEMIC_PLANNING_KEYS.subjectOutcomes, next); };
  const classChapters = chapters.filter((item) => item.className === selectedClass && item.subject === selectedSubject);
  const chapterOptions = ['All Chapters', ...classChapters.map((item) => item.name)];
  const activeOutcome = outcomes.find((item) => item.className === selectedClass && item.subject === selectedSubject);
  const filtered = useMemo(() => records.filter((item) => item.className === selectedClass && item.subject === selectedSubject && (selectedChapter === 'All Chapters' || item.chapterName === selectedChapter) && (bloomFilter === 'All Levels' || item.bloomLevel === bloomFilter) && (!search || `${item.statement} ${item.chapterName} ${item.topicName} ${item.competencyType}`.toLowerCase().includes(search.toLowerCase()))), [records, selectedClass, selectedSubject, selectedChapter, bloomFilter, search]);
  const bloomCounts = BLOOM_LEVELS.map((level) => ({ level, count: filtered.filter((item) => item.bloomLevel === level).length }));
  const totalObjectives = Math.max(1, filtered.length);
  const lowOrder = filtered.filter((item) => item.bloomLevel === 'Remember' || item.bloomLevel === 'Understand').length;
  const groups = useMemo(() => {
    const map = new Map<string, LearningObjectiveRecord[]>();
    filtered.forEach((item) => { const key = view === 'By Bloom Level' ? item.bloomLevel : view === 'By Competency Type' ? item.competencyType || 'Unmapped competency' : item.chapterName || 'No chapter linked'; map.set(key, [...(map.get(key) || []), item]); });
    return [...map.entries()];
  }, [filtered, view]);
  const update = <K extends keyof LearningObjectiveRecord,>(key: K, value: LearningObjectiveRecord[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const openNew = () => { const blank = createBlankObjective(); blank.className = selectedClass; blank.subject = selectedSubject; const chapter = classChapters.find((item) => selectedChapter === 'All Chapters' || item.name === selectedChapter) || classChapters[0]; if (chapter) { blank.chapterId = chapter.id; blank.chapterName = chapter.name; } setForm(blank); };
  const updateChapter = (id: string) => { const chapter = chapters.find((item) => item.id === id); if (chapter) setForm((current) => current ? { ...current, className: chapter.className, subject: chapter.subject, chapterId: chapter.id, chapterName: chapter.name, topicId: '', topicName: '' } : current); };
  const save = () => {
    if (!form?.statement.trim()) { setMessage('Enter a measurable objective statement.'); return; }
    const saved = { ...form, statement: form.statement.trim(), measurableCriteria: form.measurableCriteria.trim(), marksWeightage: Math.max(0, Number(form.marksWeightage)) };
    persist(records.some((item) => item.id === saved.id) ? records.map((item) => item.id === saved.id ? saved : item) : [saved, ...records]); setForm(null); setMessage('Learning objective saved.'); window.setTimeout(() => setMessage(''), 3000);
  };
  const saveOutcome = () => {
    if (!outcomeForm?.statement.trim()) { setMessage('Enter a subject-level outcome.'); return; }
    const saved = { ...outcomeForm, statement: outcomeForm.statement.trim() };
    persistOutcomes(outcomes.some((item) => item.id === saved.id) ? outcomes.map((item) => item.id === saved.id ? saved : item) : [saved, ...outcomes]); setOutcomeForm(null); setMessage('Subject-level outcome saved.'); window.setTimeout(() => setMessage(''), 3000);
  };
  const exportGuide = () => downloadPlanningCsv(`learning-objectives-${selectedClass.toLowerCase().replace(/\s/g, '-')}-${selectedSubject.toLowerCase().replace(/\s/g, '-')}.csv`, filtered.map((item) => ({ Class: item.className, Subject: item.subject, Chapter: item.chapterName, Topic: item.topicName, Objective: item.statement, StudentLanguage: item.studentLanguage, BloomLevel: item.bloomLevel, Assessment: item.howAssessed, Marks: item.marksWeightage, Competency: item.competencyType })));
  const importFile = async (file?: File) => {
    if (!file) return;
    try {
      const lines = (await file.text()).split(/\r?\n/).slice(1).filter(Boolean);
      const imported = lines.map((line, index) => { const cells = line.split(',').map((cell) => cell.trim().replace(/^"|"$/g, '')); const record = createBlankObjective(); const chapter = chapters.find((item) => item.className === (cells[0] || selectedClass) && item.subject === (cells[1] || selectedSubject) && item.name === cells[2]); return { ...record, id: newPlanningId('obj'), className: cells[0] || selectedClass, subject: cells[1] || selectedSubject, chapterId: chapter?.id || '', chapterName: chapter?.name || cells[2] || '', statement: cells[3] || `Imported objective ${index + 1}`, bloomLevel: (BLOOM_LEVELS.includes(cells[4] as typeof BLOOM_LEVELS[number]) ? cells[4] : 'Understand') as LearningObjectiveRecord['bloomLevel'], competencyType: cells[5] || 'Unmapped' }; });
      if (imported.length) { persist([...imported, ...records]); setMessage(`Imported ${imported.length} objective(s) from CSV. Expected columns: Class, Subject, Chapter, Objective, Bloom Level, Competency.`); } else setMessage('No objective rows found.');
    } catch { setMessage('Could not read the selected file. Use a CSV file.'); }
    if (importRef.current) importRef.current.value = '';
  };

  return <div className="space-y-5 p-4 md:p-6">
    <PageHeader title="🎯 Learning Objectives Master" description="Class and subject competency framework with measurable outcomes aligned to board expectations and NEP 2020." actions={<><Button onClick={openNew}><Plus className="h-4 w-4" />Add Objective</Button><Button variant="outline" onClick={() => importRef.current?.click()}><Upload className="h-4 w-4" />Import / Bulk Add</Button><Button variant="outline" onClick={exportGuide}><Download className="h-4 w-4" />Export Guide</Button><Button variant="outline" onClick={() => window.print()}><Printer className="h-4 w-4" />Print Report</Button><input ref={importRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(event) => importFile(event.target.files?.[0])} /></>} />
    <Card><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-5"><SelectField label="Class" value={selectedClass} onChange={(value) => { setSelectedClass(value); setSelectedChapter('All Chapters'); }} options={CLASSES} /><SelectField label="Subject" value={selectedSubject} onChange={(value) => { setSelectedSubject(value); setSelectedChapter('All Chapters'); }} options={SUBJECTS} /><SelectField label="Chapter" value={selectedChapter} onChange={setSelectedChapter} options={chapterOptions} /><SelectField label="Bloom’s Level" value={bloomFilter} onChange={setBloomFilter} options={['All Levels', ...BLOOM_LEVELS]} /><SelectField label="View" value={view} onChange={setView} options={['By Chapter', 'By Bloom Level', 'By Competency Type']} /></div><div className="mt-3 flex items-center gap-2"><Search className="h-4 w-4 text-slate-400" /><input className={objectivesInput} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search outcomes, topics or competencies..." /></div></Card>
    {message && <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm text-indigo-800">{message}</div>}
    <Card title={`Subject-Level Outcomes · ${selectedClass} ${selectedSubject}`} headerAction={<Button size="xs" variant="outline" onClick={() => setOutcomeForm(activeOutcome ? { ...activeOutcome } : { id: newPlanningId('outcome'), className: selectedClass, subject: selectedSubject, academicYear: '2025-26', statement: '', boardObjectives: '', nepFramework: '' })}><Edit3 className="h-3.5 w-3.5" />Add / Edit Outcome</Button>}>
      {activeOutcome ? <div className="grid gap-3 lg:grid-cols-3"><div className="rounded-lg bg-indigo-50 p-3"><p className="mb-1 text-[10px] font-bold uppercase text-indigo-700">Broad yearly outcome</p><div className="space-y-1">{activeOutcome.statement.split('\n').map((outcome, index) => <p key={`${index}-${outcome}`} className="flex items-start gap-2 text-sm text-slate-800"><span className="font-bold text-emerald-600">✓</span><span>{outcome}</span></p>)}</div></div><div className="rounded-lg bg-slate-50 p-3"><p className="mb-1 text-[10px] font-bold uppercase text-slate-500">Board alignment</p><p className="text-xs text-slate-700">{activeOutcome.boardObjectives}</p></div><div className="rounded-lg bg-emerald-50 p-3"><p className="mb-1 text-[10px] font-bold uppercase text-emerald-700">NEP 2020 framework</p><p className="text-xs text-slate-700">{activeOutcome.nepFramework}</p></div></div> : <EmptyState>No subject-level outcome defined for this selection.</EmptyState>}
    </Card>
    <div className="grid gap-4 xl:grid-cols-3"><Card title="Bloom’s Taxonomy Analysis"><div className="flex items-center gap-5"><div className="relative h-32 w-32 shrink-0 rounded-full" style={{ background: `conic-gradient(${bloomCounts.map((item, index) => `${['#6366f1','#0ea5e9','#10b981','#f59e0b','#f97316','#a855f7'][index]} ${bloomCounts.slice(0,index).reduce((sum,row)=>sum+row.count,0)/totalObjectives*100}% ${(bloomCounts.slice(0,index).reduce((sum,row)=>sum+row.count,0)+item.count)/totalObjectives*100}%`).join(', ')})` }}><div className="absolute inset-5 flex items-center justify-center rounded-full bg-white text-center"><span className="text-xl font-bold text-slate-800">{filtered.length}</span></div></div><div className="grid flex-1 grid-cols-2 gap-x-3 gap-y-1">{bloomCounts.map((item, index) => <div key={item.level} className="flex items-center gap-1.5 text-[10px]"><span className="h-2 w-2 rounded-full" style={{ backgroundColor: ['#6366f1','#0ea5e9','#10b981','#f59e0b','#f97316','#a855f7'][index] }} /><span className="text-slate-600">{item.level}</span><b className="ml-auto text-slate-800">{Math.round(item.count / Math.max(1, filtered.length) * 100)}% <span className="font-normal text-slate-400">({item.count})</span></b></div>)}</div></div><div className="mt-3 flex flex-wrap items-center justify-between gap-2 rounded-lg bg-amber-50 p-2 text-xs text-amber-900"><span>{lowOrder}/{filtered.length} low-order Remember / Understand</span>{filtered.length && lowOrder / filtered.length > 0.7 ? <Badge variant="warning">Review cognitive demand</Badge> : <Badge variant="success">Balanced coverage</Badge>}</div><p className="mt-2 text-[10px] text-slate-400">Review if low-order Remember / Understand objectives exceed 70% of the selected objective set.</p><div className="mt-3 rounded-lg border border-slate-100 bg-slate-50 p-2"><p className="mb-2 text-[10px] font-bold uppercase tracking-wide text-slate-500">Reference Bloom’s distribution</p><div className="grid grid-cols-2 gap-1 text-[10px] sm:grid-cols-3">{[{ level: 'Remember', target: '25%' }, { level: 'Understand', target: '35%' }, { level: 'Apply', target: '25%' }, { level: 'Analyse', target: '10%' }, { level: 'Evaluate', target: '3%' }, { level: 'Create', target: '2%' }].map((item) => <div key={item.level} className="flex justify-between gap-2"><span className="text-slate-600">{item.level}</span><b className="text-slate-800">{item.target}</b></div>)}</div></div></Card>
      <Card title="Subject-wise Cognitive Demand"><div className="space-y-3">{SUBJECTS.slice(0, 6).map((subject) => { const rows = records.filter((item) => item.className === selectedClass && item.subject === subject); const high = rows.filter((item) => ['Apply','Analyse','Evaluate','Create'].includes(item.bloomLevel)).length; return <div key={subject}><div className="mb-1 flex justify-between text-[11px]"><span className="text-slate-600">{subject}</span><span className="font-semibold text-slate-800">{rows.length ? Math.round(high / rows.length * 100) : 0}% higher order</span></div><div className="h-2 rounded-full bg-slate-100"><div className="h-full rounded-full bg-indigo-500" style={{ width: `${rows.length ? high / rows.length * 100 : 0}%` }} /></div></div>; })}</div></Card>
      <Card title="NEP 2020 Competency Tracker"><div className="space-y-2">{competencies.map((competency) => { const count = filtered.filter((item) => item.competencyType.toLowerCase().includes(competency.toLowerCase())).length; const status = count >= 2 ? 'Well covered' : count ? 'Partially covered' : 'Not addressed'; return <div key={competency} className="flex items-center justify-between gap-2 border-b border-slate-100 pb-1.5"><span className="text-xs text-slate-700">{competency}</span><div className="flex items-center gap-2"><span className="text-[10px] text-slate-400">{count} objective(s)</span><StatusPill status={status} /></div></div>; })}</div></Card></div>
    <Card title={`Chapter-Level Objectives · ${filtered.length} outcome(s)`} headerAction={<Badge variant="info">{selectedClass} {selectedSubject}</Badge>}>
      {groups.length === 0 ? <EmptyState>No learning objectives match these filters. Add one to start the chapter-level outcome map.</EmptyState> : <div className="space-y-4">{groups.map(([group, items]) => <section key={group} className="overflow-hidden rounded-lg border border-slate-100"><div className="flex items-center justify-between bg-slate-50 px-3 py-2"><h3 className="text-xs font-bold text-slate-800">{view === 'By Chapter' ? `Chapter · ${group}` : `${view.replace('By ', '')} · ${group}`}</h3><Badge variant="secondary">{items.length} objectives</Badge></div><div className="overflow-x-auto"><table className="w-full min-w-[950px] text-left text-xs"><thead className="text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-2">Objective</th><th className="px-3 py-2">Topic</th><th className="px-3 py-2">Bloom’s Level</th><th className="px-3 py-2">Assessment</th><th className="px-3 py-2">Board Marks</th><th className="px-3 py-2">Competency</th><th className="px-3 py-2">Status</th><th className="px-3 py-2">Action</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map((item) => <tr key={item.id}><td className="max-w-[280px] px-3 py-2"><p className="font-semibold text-slate-800">{item.statement}</p><p className="text-[10px] text-slate-400">Student: {item.studentLanguage || '—'}</p></td><td className="px-3 py-2">{item.topicName || '—'}</td><td className="px-3 py-2"><Badge variant="info">{item.bloomLevel}</Badge><p className="mt-1 text-[10px] text-slate-400">{item.actionVerb}</p></td><td className="px-3 py-2">{item.howAssessed} · {item.questionType}</td><td className="px-3 py-2">{item.marksWeightage}</td><td className="px-3 py-2">{item.competencyType}</td><td className="px-3 py-2"><StatusPill status={item.status} /></td><td className="px-3 py-2"><Button size="xs" variant="outline" onClick={() => setForm({ ...item })}>Edit</Button></td></tr>)}</tbody></table></div></section>)}</div>}
    </Card>
    <Modal isOpen={Boolean(form)} onClose={() => setForm(null)} title={form ? 'Add / Edit Learning Objective' : 'Learning Objective'} size="xl" footer={<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setForm(null)}>Cancel</Button><Button onClick={save}>Save Objective</Button></div>}>
      {form && <div className="max-h-[75vh] space-y-4 overflow-y-auto pr-1"><PlanningPanel title="Panel 1 · Objective Identity"><div className="grid gap-3 md:grid-cols-3"><TextField label="Class · from selection" value={form.className} readOnly /><TextField label="Subject · from selection" value={form.subject} readOnly /><PlanningField label="Chapter"><select className={objectivesInput} value={form.chapterId} onChange={(event) => updateChapter(event.target.value)}><option value="">Select chapter</option>{chapters.filter((item) => item.className === selectedClass && item.subject === selectedSubject).map((chapter) => <option key={chapter.id} value={chapter.id}>{chapter.name}</option>)}</select></PlanningField><PlanningField label="Topic (Optional)"><select className={objectivesInput} value={form.topicId} onChange={(event) => { const chapter = chapters.find((item) => item.id === form.chapterId); const topic = chapter?.topics.find((item) => item.id === event.target.value); update('topicId', topic?.id || ''); update('topicName', topic?.name || ''); }}><option value="">Chapter-level objective</option>{chapters.find((item) => item.id === form.chapterId)?.topics.map((topic) => <option key={topic.id} value={topic.id}>{topic.name}</option>)}</select></PlanningField><SelectField label="Objective Type" value={form.objectiveType} onChange={(value) => update('objectiveType', value as LearningObjectiveRecord['objectiveType'])} options={['Knowledge', 'Skill', 'Attitude', 'Application']} /></div></PlanningPanel>
        <PlanningPanel title="Panel 2 · Objective Statement"><div className="grid gap-3 md:grid-cols-2"><TextAreaField label="Objective Statement · Student will be able to…" value={form.statement} onChange={(value) => update('statement', value)} /><TextAreaField label="Student-friendly Language" value={form.studentLanguage} onChange={(value) => update('studentLanguage', value)} /><SelectField label="Bloom’s Level" value={form.bloomLevel} onChange={(value) => update('bloomLevel', value as LearningObjectiveRecord['bloomLevel'])} options={BLOOM_LEVELS} /><TextField label="Action Verb Used" value={form.actionVerb} onChange={(value) => update('actionVerb', value)} placeholder="Define / Explain / Calculate / Compare / Design" /><TextAreaField label="Measurable Criteria" value={form.measurableCriteria} onChange={(value) => update('measurableCriteria', value)} /><SelectField label="NEP Competency Type" value={form.competencyType} onChange={(value) => update('competencyType', value)} options={competencies} /></div></PlanningPanel>
        <PlanningPanel title="Panel 3 · Assessment Alignment"><div className="grid gap-3 md:grid-cols-3"><SelectField label="How Assessed" value={form.howAssessed} onChange={(value) => update('howAssessed', value)} options={['In-class Q&A', 'Written test', 'Practical', 'Project', 'Observation']} /><SelectField label="Question Type in Exam" value={form.questionType} onChange={(value) => update('questionType', value)} options={['MCQ', 'SA', 'LA', 'Numerical', 'Diagram', 'Practical']} /><TextField label="Marks Weightage" type="number" min="0" value={form.marksWeightage} onChange={(value) => update('marksWeightage', Number(value) || 0)} /><SelectField label="Difficulty" value={form.difficulty} onChange={(value) => update('difficulty', value as LearningObjectiveRecord['difficulty'])} options={['Easy', 'Medium', 'Hard']} /><TextField label="Linked Question Bank IDs" value={form.linkedQuestions} onChange={(value) => update('linkedQuestions', value)} placeholder="QB-103, QB-220" /></div></PlanningPanel>
        <PlanningPanel title="Panel 4 · Curriculum Mapping"><div className="grid gap-3 md:grid-cols-2"><TextField label="NCERT Reference" value={form.ncertReference} onChange={(value) => update('ncertReference', value)} /><TextField label="Board Guideline Reference" value={form.boardGuidelineReference} onChange={(value) => update('boardGuidelineReference', value)} /><TextAreaField label="Previous Class Connection" value={form.previousClassConnection} onChange={(value) => update('previousClassConnection', value)} /><TextAreaField label="Next Class Connection" value={form.nextClassConnection} onChange={(value) => update('nextClassConnection', value)} /><TextAreaField label="Cross-subject Connection" value={form.crossSubjectConnection} onChange={(value) => update('crossSubjectConnection', value)} /></div></PlanningPanel>
      </div>}
    </Modal>
    <Modal isOpen={Boolean(outcomeForm)} onClose={() => setOutcomeForm(null)} title="Subject-Level Learning Outcome" size="lg" footer={<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setOutcomeForm(null)}>Cancel</Button><Button onClick={saveOutcome}>Save Outcome</Button></div>}>
      {outcomeForm && <div className="space-y-4"><div className="grid gap-3 md:grid-cols-3"><TextField label="Class" value={outcomeForm.className} readOnly /><TextField label="Subject" value={outcomeForm.subject} readOnly /><TextField label="Academic Year" value={outcomeForm.academicYear} onChange={(value) => setOutcomeForm((current) => current ? { ...current, academicYear: value } : current)} /></div><TextAreaField label="Broad subject outcome" value={outcomeForm.statement} onChange={(value) => setOutcomeForm((current) => current ? { ...current, statement: value } : current)} /><TextAreaField label="Board objectives mapping" value={outcomeForm.boardObjectives} onChange={(value) => setOutcomeForm((current) => current ? { ...current, boardObjectives: value } : current)} /><TextAreaField label="NEP 2020 competency framework" value={outcomeForm.nepFramework} onChange={(value) => setOutcomeForm((current) => current ? { ...current, nepFramework: value } : current)} /></div>}
    </Modal>
  </div>;
}
