import React, { useMemo, useState } from 'react';
import { CalendarDays, ChevronLeft, ChevronRight, Download, Plus, Printer, WandSparkles } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Modal } from '../../../components/ui/Modal';
import { ACADEMIC_PLANNING_KEYS, DEFAULT_ATPS, DEFAULT_MONTHLY_PLANS, MONTHS, SUBJECTS, createBlankMonthlyPeriod, createBlankMonthlyPlan, downloadPlanningCsv, loadPlanningCollection, savePlanningCollection, type AnnualTeachingPlanRecord, type MonthlyPlanPeriod, type MonthlyTeachingPlanRecord } from './academicPlanningData';
import { EmptyState, PageHeader, PlanningPanel, SelectField, StatusPill, TextAreaField, TextField } from './academicPlanningUi';

const today = new Date();
const monthName = MONTHS[(today.getMonth() + 9) % 12];
const academicYear = today.getMonth() >= 3 ? String(today.getFullYear()) : String(today.getFullYear() - 1);

export function MonthlyTeachingPlan() {
  const [plans, setPlans] = useState<MonthlyTeachingPlanRecord[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.monthlyPlans, DEFAULT_MONTHLY_PLANS));
  const [atps] = useState<AnnualTeachingPlanRecord[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.atps, DEFAULT_ATPS));
  const [month, setMonth] = useState('November');
  const [year, setYear] = useState('2025');
  const [classFilter, setClassFilter] = useState('Class 10');
  const [subjectFilter, setSubjectFilter] = useState('Science');
  const [teacherFilter, setTeacherFilter] = useState('All Teachers');
  const [statusFilter, setStatusFilter] = useState('All Statuses');
  const [view, setView] = useState('All Plans');
  const [form, setForm] = useState<MonthlyTeachingPlanRecord | null>(null);
  const [message, setMessage] = useState('');
  const persist = (next: MonthlyTeachingPlanRecord[]) => { setPlans(next); savePlanningCollection(ACADEMIC_PLANNING_KEYS.monthlyPlans, next); };
  const update = <K extends keyof MonthlyTeachingPlanRecord,>(key: K, value: MonthlyTeachingPlanRecord[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const updatePeriod = (id: string, patch: Partial<MonthlyPlanPeriod>) => setForm((current) => current ? { ...current, periods: current.periods.map((period) => period.id === id ? { ...period, ...patch } : period) } : current);
  const filtered = useMemo(() => plans.filter((item) => item.month === month && item.year === year && (classFilter === 'All Classes' || item.className === classFilter) && (subjectFilter === 'All Subjects' || item.subject === subjectFilter) && (teacherFilter === 'All Teachers' || item.teacher === teacherFilter) && (statusFilter === 'All Statuses' || item.status === statusFilter)), [plans, month, year, classFilter, subjectFilter, teacherFilter, statusFilter]);
  const teachers = [...new Set(plans.map((item) => item.teacher).concat(atps.map((item) => item.teacher)))];
  const persistMessage = (text: string) => { setMessage(text); window.setTimeout(() => setMessage(''), 3500); };
  const moveMonth = (delta: number) => { const index = MONTHS.indexOf(month); const next = index + delta; const wrapped = (next + MONTHS.length) % MONTHS.length; if (next < 0) setYear(String(Number(year) - 1)); if (next >= MONTHS.length) setYear(String(Number(year) + 1)); setMonth(MONTHS[wrapped]); };
  const openNew = () => { const blank = createBlankMonthlyPlan(); blank.month = month; blank.year = year; blank.className = classFilter === 'All Classes' ? 'Class 10' : classFilter; blank.subject = subjectFilter === 'All Subjects' ? 'Science' : subjectFilter; setForm(blank); };
  const openEdit = (record: MonthlyTeachingPlanRecord) => setForm({ ...record, submitTo: record.submitTo || `HOD — ${record.subject}`, submittedDate: record.submittedDate || '', hodName: record.hodName || `HOD — ${record.subject}`, hodFeedback: record.hodFeedback || '', hodReviewedOn: record.hodReviewedOn || '', periods: record.periods.map((period) => ({ ...period })) });
  const autoPopulate = () => {
    if (!form) return;
    const atp = atps.find((item) => item.className === form.className && item.subject === form.subject && item.academicYear === (form.year === '2025' ? '2025-26' : `${form.year}-${String((Number(form.year) + 1) % 100).padStart(2, '0')}`) && (item.status === 'HOD Approved' || item.status === 'Principal Viewed'));
    if (!atp) { persistMessage('No approved ATP is linked for this class and subject.'); return; }
    const chapters = Object.entries(atp.monthlyDistribution).filter(([, months]) => Number(months[form.month] || 0) > 0).map(([chapter]) => chapter);
    const periods = chapters.map((chapter, index) => ({ ...createBlankMonthlyPeriod(), weekNumber: index % 4 + 1, chapter, topic: 'Plan topic from Curriculum Master' }));
    setForm((current) => current ? { ...current, linkedAtpId: atp.id, chaptersToCover: chapters.join('; '), periods: [...current.periods, ...periods], totalPeriodsPlanned: Math.max(current.totalPeriodsPlanned, periods.length) } : current);
    persistMessage(`Pulled ${chapters.length} chapter(s) from approved ATP ${atp.id}.`);
  };
  const save = (action: MonthlyTeachingPlanRecord['status']) => {
    if (!form || !form.teacher || !form.subject) { persistMessage('Select a teacher and subject before saving.'); return; }
    if (action === 'HOD Viewed' && !(form.hodFeedback || '').trim()) { persistMessage('Add HOD feedback before recording the review.'); return; }
    const completed = form.periods.filter((item) => item.status === 'Completed').length;
    const today = new Date().toISOString().slice(0, 10);
    const saved = { ...form, status: action, submittedDate: action === 'Submitted' ? today : form.submittedDate, hodReviewedOn: action === 'HOD Viewed' ? today : form.hodReviewedOn, completionPercent: form.periods.length ? Math.round(completed / form.periods.length * 100) : form.completionPercent, totalPeriodsPlanned: Math.max(0, Number(form.totalPeriodsPlanned) || 0) };
    persist(plans.some((item) => item.id === saved.id) ? plans.map((item) => item.id === saved.id ? saved : item) : [saved, ...plans]); setForm(null); persistMessage(action === 'Submitted' ? 'Monthly teaching plan submitted for HOD review.' : action === 'HOD Viewed' ? 'HOD review recorded on the monthly plan.' : 'Monthly teaching plan draft saved.');
  };
  const addPeriod = () => { if (!form) return; setForm({ ...form, periods: [...form.periods, { ...createBlankMonthlyPeriod(), weekNumber: Math.min(4, form.periods.length + 1), periodNumber: form.periods.length + 1 }] }); };
  const exportPlan = (record: MonthlyTeachingPlanRecord) => downloadPlanningCsv(`monthly-plan-${record.className}-${record.month}-${record.year}.csv`, record.periods.map((item) => ({ Week: item.weekNumber, Date: item.date, Period: item.periodNumber, Chapter: item.chapter, Topic: item.topic, SubTopic: item.subTopic, Method: item.teachingMethod, Resources: item.resources, ExpectedOutcome: item.expectedOutcome, Status: item.status, Note: item.note })));
  const shareWithParents = (record: MonthlyTeachingPlanRecord) => { exportPlan(record); persistMessage(`Parent-ready ${record.className} ${record.subject} monthly plan exported as CSV.`); };
  const allRows = filtered.flatMap((item) => item.periods);
  const planned = form?.periods.length || 0;
  const done = form?.periods.filter((item) => item.status === 'Completed').length || 0;
  const startedChapters = [...new Set(form?.periods.filter((item) => item.status !== 'Planned').map((item) => item.chapter).filter(Boolean) || [])];
  const completedChapters = [...new Set(form?.periods.filter((item) => item.status === 'Completed').map((item) => item.chapter).filter(Boolean) || [])];
  const myDepartment = atps.find((item) => item.teacher === 'Mr. R. Kumar')?.department || 'Science';
  const statusForView = view === 'My Plans' ? filtered.filter((item) => item.teacher === 'Mr. R. Kumar') : view === 'Department Plans' ? filtered.filter((item) => atps.some((atp) => atp.teacher === item.teacher && atp.department === myDepartment)) : filtered;

  return <div className="space-y-5 p-4 md:p-6">
    <PageHeader title="📅 Monthly Teaching Plan" description="Plan week-by-week chapters and topics, then track completion and month-end carry-over." actions={<><Button onClick={openNew}><Plus className="h-4 w-4" />Create Monthly Plan</Button><Button variant="outline" onClick={() => window.print()}><Printer className="h-4 w-4" />Print / PDF</Button></>} />
    <Card><div className="flex flex-wrap items-end justify-between gap-3"><div className="flex items-end gap-2"><Button size="sm" variant="outline" onClick={() => moveMonth(-1)}><ChevronLeft className="h-4 w-4" />Previous</Button><div className="min-w-44 text-center"><p className="text-[10px] font-semibold uppercase text-slate-500">Selected month</p><p className="text-lg font-bold text-slate-900">{month} {year}</p></div><Button size="sm" variant="outline" onClick={() => moveMonth(1)}>Next<ChevronRight className="h-4 w-4" /></Button><Button size="sm" variant="ghost" onClick={() => { setMonth(monthName); setYear(academicYear); }}><CalendarDays className="h-4 w-4" />Current Month</Button></div><div className="grid flex-1 gap-3 sm:grid-cols-2 lg:grid-cols-5"><SelectField label="Class" value={classFilter} onChange={setClassFilter} options={['All Classes','Class 8','Class 9','Class 10']} /><SelectField label="Subject" value={subjectFilter} onChange={setSubjectFilter} options={['All Subjects', ...SUBJECTS]} /><SelectField label="Teacher" value={teacherFilter} onChange={setTeacherFilter} options={['All Teachers', ...teachers]} /><SelectField label="Status" value={statusFilter} onChange={setStatusFilter} options={['All Statuses','Draft','Submitted','HOD Viewed']} /><SelectField label="View" value={view} onChange={setView} options={['My Plans','Department Plans','All Plans']} /></div></div></Card>
    {message && <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm text-indigo-800">{message}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card><p className="text-2xl font-bold text-indigo-700">{statusForView.length}</p><p className="text-xs text-slate-500">Teacher–class plans this month</p></Card><Card><p className="text-2xl font-bold text-emerald-700">{statusForView.reduce((sum, item) => sum + item.completionPercent, 0) ? Math.round(statusForView.reduce((sum, item) => sum + item.completionPercent, 0) / Math.max(1, statusForView.length)) : 0}%</p><p className="text-xs text-slate-500">Average completion</p></Card><Card><p className="text-2xl font-bold text-amber-700">{statusForView.filter((item) => item.status === 'Draft').length}</p><p className="text-xs text-slate-500">Draft / not submitted</p></Card><Card><p className="text-2xl font-bold text-rose-700">{statusForView.filter((item) => item.status === 'Submitted').length}</p><p className="text-xs text-slate-500">Awaiting HOD review</p></Card><Card><p className="text-2xl font-bold text-sky-700">{statusForView.reduce((sum, item) => sum + item.totalPeriodsPlanned, 0)}</p><p className="text-xs text-slate-500">Periods planned</p></Card></div>
    <Card title={`Monthly Plan Status · ${month} ${year}`} noPadding><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase text-slate-500"><tr><th className="px-3 py-3">Teacher</th><th className="px-3 py-3">Class / Section</th><th className="px-3 py-3">Subject</th><th className="px-3 py-3">Linked ATP</th><th className="px-3 py-3">Periods</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Completion</th><th className="px-3 py-3">HOD Review</th><th className="px-3 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{statusForView.map((item) => <tr key={item.id}><td className="px-3 py-3 font-semibold">{item.teacher}</td><td className="px-3 py-3">{item.className} · {item.section}</td><td className="px-3 py-3">{item.subject}</td><td className="px-3 py-3 text-xs">{item.linkedAtpId || '—'}</td><td className="px-3 py-3">{item.totalPeriodsPlanned}/{item.totalPeriodsAvailable}</td><td className="px-3 py-3"><StatusPill status={item.status} /></td><td className="px-3 py-3"><div className="flex items-center gap-2"><div className="h-2 w-20 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{ width: `${item.completionPercent}%` }} /></div>{item.completionPercent}%</div></td><td className="px-3 py-3 text-[10px]">{item.hodReviewedOn ? <><b>{item.hodName}</b><p className="text-slate-400">Reviewed {item.hodReviewedOn}</p></> : item.status === 'Submitted' ? <span className="text-amber-700">Awaiting HOD · {item.submitTo}</span> : '—'}{item.hodFeedback && <p className="mt-1 max-w-44 text-slate-500">{item.hodFeedback}</p>}</td><td className="px-3 py-3"><div className="flex gap-1"><Button size="xs" variant="outline" onClick={() => openEdit(item)}>View / Edit</Button><Button size="xs" variant="outline" onClick={() => exportPlan(item)}><Download className="h-3 w-3" />Export</Button><Button size="xs" variant="outline" onClick={() => shareWithParents(item)}>Share</Button></div></td></tr>)}{statusForView.length === 0 && <tr><td colSpan={9} className="px-4 py-10 text-center text-sm text-slate-400">No monthly plans for this month and filter selection.</td></tr>}</tbody></table></div></Card>
    <Card title="Period Completion Snapshot"><div className="grid gap-4 md:grid-cols-2"><div><div className="mb-2 flex justify-between text-xs"><span>Completed periods across displayed plans</span><span>{allRows.filter((row) => row.status === 'Completed').length}/{allRows.length}</span></div><div className="h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-emerald-500" style={{ width: `${allRows.length ? allRows.filter((row) => row.status === 'Completed').length / allRows.length * 100 : 0}%` }} /></div><p className="mt-2 text-[10px] text-slate-500">Progress is recalculated from the current period statuses (Completed, Planned, Skipped and Postponed).</p></div><div className="flex flex-wrap gap-2">{['Planned','Completed','Skipped','Postponed','Substituted'].map((status) => <Badge key={status} variant={status === 'Completed' ? 'success' : status === 'Skipped' ? 'danger' : 'info'}>{status}: {allRows.filter((row) => row.status === status).length}</Badge>)}</div></div></Card>
    <Modal isOpen={Boolean(form)} onClose={() => setForm(null)} title={form ? `${form.month} ${form.year} · Monthly Teaching Plan` : 'Monthly Plan'} size="xl" footer={<div className="flex flex-wrap justify-end gap-2"><Button variant="outline" onClick={() => setForm(null)}>Cancel</Button><Button variant="outline" onClick={() => save('Draft')}>Save Draft</Button><Button onClick={() => save('Submitted')}><CalendarDays className="h-4 w-4" />Submit to HOD</Button>{form && (form.status === 'Submitted' || form.status === 'HOD Viewed') && <Button variant="outline" onClick={() => save('HOD Viewed')}>{form.status === 'Submitted' ? 'Record HOD Review' : 'Save HOD Review'}</Button>}</div>}>
      {form && <div className="max-h-[76vh] space-y-4 overflow-y-auto pr-1"><PlanningPanel title="Plan Header Information"><div className="grid gap-3 md:grid-cols-3"><TextField label="Teacher" value={form.teacher} onChange={(value) => update('teacher', value)} /><SelectField label="Class" value={form.className} onChange={(value) => update('className', value)} options={['Class 8','Class 9','Class 10']} /><TextField label="Section" value={form.section} onChange={(value) => update('section', value)} /><SelectField label="Subject" value={form.subject} onChange={(value) => update('subject', value)} options={SUBJECTS} /><SelectField label="Month" value={form.month} onChange={(value) => update('month', value)} options={MONTHS} /><TextField label="Year" value={form.year} onChange={(value) => update('year', value)} /><TextField label="Linked ATP" value={form.linkedAtpId} readOnly /><TextAreaField label="Chapters to Cover This Month" value={form.chaptersToCover} onChange={(value) => update('chaptersToCover', value)} /><div className="flex items-end"><Button variant="outline" onClick={autoPopulate}><WandSparkles className="h-4 w-4" />Auto-populate from ATP</Button></div><TextField label="Total Periods Available" type="number" min="0" value={form.totalPeriodsAvailable} onChange={(value) => update('totalPeriodsAvailable', Number(value) || 0)} /><TextField label="Total Periods Planned" type="number" min="0" value={form.totalPeriodsPlanned} onChange={(value) => update('totalPeriodsPlanned', Number(value) || 0)} /><TextField label="Buffer Periods" type="number" min="0" value={form.bufferPeriods} onChange={(value) => update('bufferPeriods', Number(value) || 0)} /></div></PlanningPanel>
        <PlanningPanel title="Week-by-Week Plan Table" description="Add one row for every planned class period, including method, resource and expected outcome."><div className="mb-2 flex justify-end"><Button size="xs" variant="outline" onClick={addPeriod}><Plus className="h-3.5 w-3.5" />Add Period</Button></div>{form.periods.length ? <div className="space-y-3">{form.periods.map((period) => <div key={period.id} className="grid gap-2 rounded-lg border border-slate-200 bg-slate-50 p-3 md:grid-cols-4"><TextField label="Week Number" type="number" min="1" max="5" value={period.weekNumber} onChange={(value) => updatePeriod(period.id, { weekNumber: Number(value) || 1 })} /><TextField label="Date" type="date" value={period.date} onChange={(value) => updatePeriod(period.id, { date: value })} /><TextField label="Period Number" type="number" min="1" value={period.periodNumber} onChange={(value) => updatePeriod(period.id, { periodNumber: Number(value) || 1 })} /><SelectField label="Status" value={period.status} onChange={(value) => updatePeriod(period.id, { status: value as MonthlyPlanPeriod['status'] })} options={['Planned','Completed','Skipped','Postponed']} /><TextField label="Chapter" value={period.chapter} onChange={(value) => updatePeriod(period.id, { chapter: value })} /><TextField label="Topic" value={period.topic} onChange={(value) => updatePeriod(period.id, { topic: value })} /><TextField label="Sub-topic" value={period.subTopic} onChange={(value) => updatePeriod(period.id, { subTopic: value })} /><SelectField label="Teaching Method" value={period.teachingMethod} onChange={(value) => updatePeriod(period.id, { teachingMethod: value })} options={['Lecture','Demo','Discussion','Activity','Lab','Test','Revision']} /><TextField label="Resources to Use" value={period.resources} onChange={(value) => updatePeriod(period.id, { resources: value })} /><TextField label="Expected Outcome" value={period.expectedOutcome} onChange={(value) => updatePeriod(period.id, { expectedOutcome: value })} /><SelectField label="Student Understanding" value={period.understanding} onChange={(value) => updatePeriod(period.id, { understanding: value })} options={['Excellent','Good','Fair','Needs Revision']} /><TextField label="Skipped / Postponed Reason" value={period.reason} onChange={(value) => updatePeriod(period.id, { reason: value })} /><TextField label="Moved To Date" type="date" value={period.movedToDate} onChange={(value) => updatePeriod(period.id, { movedToDate: value })} /><TextField label="Daily Note" value={period.note} onChange={(value) => updatePeriod(period.id, { note: value })} /><Button size="xs" variant="ghost" className="self-end" onClick={() => update('periods', form.periods.filter((item) => item.id !== period.id))}>Remove period</Button></div>)}</div> : <EmptyState>No period rows yet. Add a row or populate topics from the approved ATP.</EmptyState>}</PlanningPanel>
        <PlanningPanel title="Special Periods This Month"><div className="grid gap-3 md:grid-cols-2"><TextAreaField label="Test Dates · Assessment Calendar" value={form.testDates} onChange={(value) => update('testDates', value)} /><TextAreaField label="Lab Dates" value={form.labDates} onChange={(value) => update('labDates', value)} /><TextAreaField label="Revision Dates" value={form.revisionDates} onChange={(value) => update('revisionDates', value)} /><TextAreaField label="Assignment Due Dates" value={form.assignmentDueDates} onChange={(value) => update('assignmentDueDates', value)} /><TextAreaField label="Holiday Impact" value={form.holidayImpact} onChange={(value) => update('holidayImpact', value)} /></div></PlanningPanel>
        <PlanningPanel title="Month Summary & Review"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="rounded bg-indigo-50 p-3 text-xs">Theory periods <b className="block text-xl">{form.periods.filter((item) => !['Lab','Test','Revision'].includes(item.teachingMethod)).length}</b></div><div className="rounded bg-sky-50 p-3 text-xs">Lab periods <b className="block text-xl">{form.periods.filter((item) => item.teachingMethod === 'Lab').length}</b></div><div className="rounded bg-amber-50 p-3 text-xs">Test periods <b className="block text-xl">{form.periods.filter((item) => item.teachingMethod === 'Test').length}</b></div><div className="rounded bg-emerald-50 p-3 text-xs">Revision periods <b className="block text-xl">{form.periods.filter((item) => item.teachingMethod === 'Revision').length}</b></div></div><div className="grid gap-3 md:grid-cols-2"><TextAreaField label="Topics Carrying Over" value={form.topicsCarryingOver} onChange={(value) => update('topicsCarryingOver', value)} /><TextAreaField label="Student Performance Observation" value={form.studentObservation} onChange={(value) => update('studentObservation', value)} /><TextAreaField label="Resources That Worked Well" value={form.resourcesWorked} onChange={(value) => update('resourcesWorked', value)} /><TextAreaField label="Resources That Didn't Work" value={form.resourcesNotWorked} onChange={(value) => update('resourcesNotWorked', value)} /><TextAreaField label="Significant Events Impacting Teaching" value={form.significantEvents} onChange={(value) => update('significantEvents', value)} /></div><div className="rounded-lg bg-slate-50 p-3 text-xs"><b>Started this month:</b> {startedChapters.join(', ') || '—'}<br /><b>Completed this month:</b> {completedChapters.join(', ') || '—'}<br /><b>Completion:</b> {done}/{planned} planned periods ({form.periods.length ? Math.round(done / planned * 100) : 0}%)</div></PlanningPanel>
        <PlanningPanel title="HOD Submission & Review" description="Track monthly plan submission, review feedback and the HOD review date."><div className="grid gap-3 md:grid-cols-3"><TextField label="Submit To" value={form.submitTo} onChange={(value) => update('submitTo', value)} /><TextField label="Submitted Date" type="date" value={form.submittedDate} onChange={(value) => update('submittedDate', value)} /><TextField label="HOD Name" value={form.hodName} onChange={(value) => update('hodName', value)} /><TextField label="HOD Reviewed On" type="date" value={form.hodReviewedOn} onChange={(value) => update('hodReviewedOn', value)} /><SelectField label="Workflow Status" value={form.status} onChange={(value) => update('status', value as MonthlyTeachingPlanRecord['status'])} options={['Draft','Submitted','HOD Viewed']} /><TextAreaField label="HOD Feedback" value={form.hodFeedback} onChange={(value) => update('hodFeedback', value)} /></div><p className="mt-2 text-[10px] text-slate-500">“Record HOD Review” saves the feedback and marks this plan as HOD Viewed.</p></PlanningPanel>
      </div>}
    </Modal>
  </div>;
}
