import React, { useMemo, useRef, useState } from 'react';
import { BookOpen, Download, Edit3, FileUp, Plus, Search, Share2, Trash2 } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Modal } from '../../../components/ui/Modal';
import { ACADEMIC_PLANNING_KEYS, CLASSES, DEFAULT_CURRICULUM_CHAPTERS, DEFAULT_RESOURCES, RESOURCE_TYPES, createBlankResource, downloadPlanningCsv, loadPlanningCollection, newPlanningId, savePlanningCollection, type CurriculumChapter, type ResourceRecord } from './academicPlanningData';
import { CheckField, EmptyState, PageHeader, PlanningPanel, SelectField, StatusPill, TextAreaField, TextField } from './academicPlanningData';

const inputClass = 'w-full rounded-lg border border-slate-300 px-3 py-2 text-sm text-slate-800 focus:border-indigo-500 focus:outline-none focus:ring-2 focus:ring-indigo-100';
const parseCsvLine = (line: string) => {
  const cells: string[] = []; let cell = ''; let quoted = false;
  for (let index = 0; index < line.length; index += 1) {
    const character = line.charAt(index);
    if (character === '"' && quoted && line.charAt(index + 1) === '"') { cell += '"'; index += 1; }
    else if (character === '"') quoted = !quoted;
    else if (character === ',' && !quoted) { cells.push(cell.trim()); cell = ''; }
    else cell += character;
  }
  cells.push(cell.trim()); return cells;
};

export function TextbookResourceMaster() {
  const [resources, setResources] = useState<ResourceRecord[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.resources, DEFAULT_RESOURCES));
  const [chapters] = useState<CurriculumChapter[]>(() => loadPlanningCollection(ACADEMIC_PLANNING_KEYS.chapters, DEFAULT_CURRICULUM_CHAPTERS));
  const [search, setSearch] = useState('');
  const [classFilter, setClassFilter] = useState('All Classes');
  const [subjectFilter, setSubjectFilter] = useState('All Subjects');
  const [chapterFilter, setChapterFilter] = useState('All Chapters');
  const [typeFilter, setTypeFilter] = useState('All Types');
  const [availabilityFilter, setAvailabilityFilter] = useState('All Availability');
  const [formatFilter, setFormatFilter] = useState('All Formats');
  const [form, setForm] = useState<ResourceRecord | null>(null);
  const [message, setMessage] = useState('');
  const importRef = useRef<HTMLInputElement>(null);
  const persist = (next: ResourceRecord[]) => { setResources(next); savePlanningCollection(ACADEMIC_PLANNING_KEYS.resources, next); };
  const update = <K extends keyof ResourceRecord,>(key: K, value: ResourceRecord[K]) => setForm((current) => current ? { ...current, [key]: value } : current);
  const mappedChapters = form ? chapters.filter((chapter) => form.classes.includes(chapter.className) && (!form.subjects.trim() || form.subjects.split(',').map((subject) => subject.trim().toLowerCase()).includes(chapter.subject.toLowerCase()))) : [];
  const toggleMappedChapter = (name: string) => { if (!form) return; const selected = form.chapters.split(';').map((chapter) => chapter.trim()).filter(Boolean); update('chapters', (selected.includes(name) ? selected.filter((chapter) => chapter !== name) : [...selected, name]).join('; ')); };
  const filtered = useMemo(() => resources.filter((item) => (!search || `${item.name} ${item.shortName} ${item.subjects} ${item.authorPublisher} ${item.chapters}`.toLowerCase().includes(search.toLowerCase())) && (classFilter === 'All Classes' || item.classes.includes(classFilter)) && (subjectFilter === 'All Subjects' || item.subjects.toLowerCase().includes(subjectFilter.toLowerCase())) && (chapterFilter === 'All Chapters' || item.chapters.toLowerCase().includes(chapterFilter.toLowerCase())) && (typeFilter === 'All Types' || item.type === typeFilter) && (availabilityFilter === 'All Availability' || item.availability === availabilityFilter) && (formatFilter === 'All Formats' || item.format === formatFilter)), [resources, search, classFilter, subjectFilter, chapterFilter, typeFilter, availabilityFilter, formatFilter]);
  const chapterGaps = chapters.filter((chapter) => !resources.some((resource) => resource.status === 'Active' && resource.classes.includes(chapter.className) && resource.subjects.toLowerCase().includes(chapter.subject.toLowerCase()) && resource.chapters.toLowerCase().includes(chapter.name.toLowerCase())));
  const physical = resources.filter((item) => item.format.includes('Physical')).length;
  const digital = resources.filter((item) => item.format.includes('Digital') || item.format.includes('Online') || item.format === 'Both').length;
  const outdated = resources.filter((item) => Number(item.editionYear.match(/\d{4}/)?.[0] || 0) > 0 && Number(item.editionYear.match(/\d{4}/)?.[0] || 0) < 2023);
  const underused = resources.filter((item) => !item.chapters.trim() && !item.topics.trim());
  const wishlist = resources.filter((item) => item.procurementRequested);
  const needsSource = resources.filter((item) => item.availability === 'Needs to be sourced');
  const resourceTypeSummary = [
    { name: 'Textbooks', count: resources.filter((item) => item.type === 'Prescribed Textbook').length },
    { name: 'Reference', count: resources.filter((item) => item.type === 'Reference Book').length },
    { name: 'Digital', count: resources.filter((item) => item.type === 'Digital Content (App)' || item.type === 'Online Course / URL').length },
    { name: 'Videos', count: resources.filter((item) => item.type === 'Video').length },
    { name: 'Worksheets', count: resources.filter((item) => item.type === 'Worksheet').length },
    { name: 'Lab Equipment', count: resources.filter((item) => item.type === 'Lab Equipment' || item.type === 'Lab Manual').length },
    { name: 'Visual Aids', count: resources.filter((item) => item.type === 'Visual Aid').length },
  ];
  const exportCsv = (rows: ResourceRecord[]) => downloadPlanningCsv('textbook-resource-list.csv', rows.map((item) => ({ Name: item.name, Type: item.type, Subject: item.subjects, Classes: item.classes.join('; '), Chapters: item.chapters, URL: item.url, Availability: item.availability, Format: item.format, AddedBy: item.addedBy, Status: item.status })));
  const save = () => {
    if (!form?.name.trim()) { setMessage('Enter a resource name before saving.'); return; }
    const saved = { ...form, name: form.name.trim(), shortName: form.shortName || form.name.trim(), cost: Math.max(0, Number(form.cost)), copies: Math.max(0, Number(form.copies)), classes: form.classes.length ? form.classes : [classFilter === 'All Classes' ? 'Class 10' : classFilter] };
    persist(resources.some((item) => item.id === saved.id) ? resources.map((item) => item.id === saved.id ? saved : item) : [saved, ...resources]); setForm(null); setMessage(`“${saved.name}” saved to the resource master.`); window.setTimeout(() => setMessage(''), 3000);
  };
  const requestResource = () => { const blank = createBlankResource(); blank.procurementRequested = true; blank.availability = 'Needs to be sourced'; setForm(blank); };
  const toggleClass = (className: string) => update('classes', form?.classes.includes(className) ? form.classes.filter((item) => item !== className) : [...(form?.classes || []), className]);
  const setAvailability = (value: string) => setForm((current) => current ? { ...current, availability: value as ResourceRecord['availability'], procurementRequested: value === 'Needs to be sourced' ? true : current.procurementRequested } : current);
  const importCsv = async (file?: File) => {
    if (!file) return;
    try {
      const lines = (await file.text()).split(/\r?\n/).slice(1).filter(Boolean);
      const imported = lines.map((line, index) => {
        const cells = parseCsvLine(line); const resource = createBlankResource();
        const resourceType = cells[1] || ''; const availability = cells[6] || ''; const format = cells[7] || ''; const addedBy = cells[8] || ''; const status = cells[9] || '';
        return { ...resource, id: newPlanningId('resource'), name: cells[0] || `Imported resource ${index + 1}`, type: RESOURCE_TYPES.includes(resourceType as typeof RESOURCE_TYPES[number]) ? resourceType : 'Prescribed Textbook', subjects: cells[2] || '', classes: (cells[3] || 'Class 10').split(';').map((item) => item.trim()), chapters: cells[4] || '', url: cells[5] || '', availability: (['Available in school', 'Needs to be sourced', 'Online only'].includes(availability) ? availability : 'Needs to be sourced') as ResourceRecord['availability'], procurementRequested: availability === 'Needs to be sourced', format: ['Physical (Book)', 'Digital File', 'Online URL', 'Both'].includes(format) ? format : resource.format, addedBy: ['Teacher', 'HOD', 'Admin'].includes(addedBy) ? addedBy : resource.addedBy, status: ['Active', 'Inactive'].includes(status) ? status as ResourceRecord['status'] : resource.status };
      });
      if (imported.length) { persist([...imported, ...resources]); setMessage(`Imported ${imported.length} resource row(s) from CSV.`); } else setMessage('No resource rows found in the CSV.');
    } catch { setMessage('Unable to read this file. Please select a CSV.'); }
    if (importRef.current) importRef.current.value = '';
  };
  const toggleProcurement = (record: ResourceRecord) => persist(resources.map((item) => item.id === record.id ? { ...item, procurementRequested: !item.procurementRequested } : item));
  const remove = (record: ResourceRecord) => { if (window.confirm(`Delete ${record.name}?`)) persist(resources.filter((item) => item.id !== record.id)); };

  return <div className="space-y-5 p-4 md:p-6">
    <PageHeader title="📚 Textbook & Resource Master" description="Central catalogue for physical and digital learning resources, curriculum links, availability and procurement." actions={<><Button onClick={() => setForm(createBlankResource())}><Plus className="h-4 w-4" />Add Resource</Button><Button variant="outline" onClick={() => importRef.current?.click()}><FileUp className="h-4 w-4" />Bulk Import</Button><Button variant="outline" onClick={() => exportCsv(filtered)}><Download className="h-4 w-4" />Export List</Button><Button variant="outline" onClick={() => exportCsv(resources.filter((item) => item.type === 'Prescribed Textbook'))}><Share2 className="h-4 w-4" />Books Required</Button><Button variant="outline" onClick={() => exportCsv(resources.filter((item) => item.type === 'Prescribed Textbook'))}><Share2 className="h-4 w-4" />Share Prescribed List</Button><input ref={importRef} type="file" accept=".csv,text/csv" className="hidden" onChange={(event) => importCsv(event.target.files?.[0])} /></>} />
    <Card><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-7"><div className="relative"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400" /><input className={`${inputClass} pl-9`} value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Search resources..." /></div><SelectField label="Class" value={classFilter} onChange={setClassFilter} options={['All Classes', ...CLASSES]} /><SelectField label="Subject" value={subjectFilter} onChange={setSubjectFilter} options={['All Subjects', ...new Set([...resources.flatMap((item) => item.subjects.split(',').map((subject) => subject.trim()).filter(Boolean))])]} /><SelectField label="Chapter" value={chapterFilter} onChange={setChapterFilter} options={['All Chapters', ...new Set(chapters.map((chapter) => chapter.name))]} /><SelectField label="Resource Type" value={typeFilter} onChange={setTypeFilter} options={['All Types', ...RESOURCE_TYPES]} /><SelectField label="Availability" value={availabilityFilter} onChange={setAvailabilityFilter} options={['All Availability', 'Available in school', 'Needs to be sourced', 'Online only']} /><SelectField label="Format" value={formatFilter} onChange={setFormatFilter} options={['All Formats', 'Physical (Book)', 'Digital File', 'Online URL', 'Both']} /></div></Card>
    {message && <div className="rounded-lg border border-indigo-200 bg-indigo-50 px-4 py-2 text-sm text-indigo-800">{message}</div>}
    <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-5"><Card><p className="text-2xl font-bold text-indigo-700">{resources.length}</p><p className="text-xs text-slate-500">Active resource records</p></Card><Card><p className="text-2xl font-bold text-emerald-700">{resources.filter((item) => item.availability === 'Available in school').length}</p><p className="text-xs text-slate-500">Available in school</p></Card><Card><p className="text-2xl font-bold text-orange-700">{needsSource.length}</p><p className="text-xs text-slate-500">Needs to be sourced</p></Card><Card><p className="text-2xl font-bold text-amber-700">{chapterGaps.length}</p><p className="text-xs text-slate-500">Chapters with resource gaps</p></Card><Card><p className="text-2xl font-bold text-rose-700">{wishlist.length}</p><p className="text-xs text-slate-500">Procurement wishlist items</p></Card></div>
    <div className="grid gap-4 xl:grid-cols-2"><Card title="Resource Availability Dashboard"><div className="grid gap-3 sm:grid-cols-2"><div className="rounded-lg bg-indigo-50 p-3"><p className="text-[10px] font-bold uppercase text-indigo-700">Format mix</p><p className="mt-2 text-sm font-semibold text-slate-800">{physical} physical · {digital} digital / online</p><div className="mt-2 flex h-2 overflow-hidden rounded-full bg-white"><div className="bg-indigo-500" style={{ width: `${resources.length ? physical / resources.length * 100 : 0}%` }} /><div className="bg-cyan-400" style={{ width: `${resources.length ? digital / resources.length * 100 : 0}%` }} /></div></div><div className="rounded-lg bg-amber-50 p-3"><p className="text-[10px] font-bold uppercase text-amber-700">Update & use alerts</p><p className="mt-2 text-xs text-slate-700">{outdated.length} old edition(s) · {underused.length} resource(s) not linked to a chapter/topic</p></div></div><div className="mt-3 space-y-1">{chapterGaps.slice(0, 5).map((chapter) => <p key={chapter.id} className="flex items-center gap-2 text-xs text-rose-700"><BookOpen className="h-3.5 w-3.5" />{chapter.className} · {chapter.subject} · {chapter.name} — resource needed</p>)}</div></Card><Card title="Resource Procurement Wishlist" headerAction={<Button size="xs" onClick={requestResource}><Plus className="h-3.5 w-3.5" />Request Resource</Button>}>{wishlist.length ? <div className="space-y-2">{wishlist.map((item) => <div key={item.id} className="flex flex-wrap items-center justify-between gap-2 rounded-lg border border-slate-100 p-3"><div><p className="text-xs font-bold text-slate-800">{item.name || 'New requested resource'}</p><p className="text-[10px] text-slate-500">{item.type} · {item.subjects || 'Subject pending'} · {item.cost ? `₹${item.cost}` : 'Cost not specified'}</p></div><div className="flex items-center gap-2"><StatusPill status={item.availability} /><Button size="xs" variant="outline" onClick={() => toggleProcurement(item)}>{item.procurementRequested ? 'Mark reviewed' : 'Add to wishlist'}</Button><Button size="xs" variant="outline" onClick={() => setForm({ ...item })}>Review</Button></div></div>)}</div> : <EmptyState>No resource requests. Use “Request Resource” to add an item for admin review.</EmptyState>}<p className="mt-3 text-[10px] text-slate-400">Procurement actions are a frontend workflow; purchase / expense modules are not connected here.</p></Card></div>
    <Card title="Resource Types Summary"><div className="grid grid-cols-2 gap-2 sm:grid-cols-4 xl:grid-cols-8">{resourceTypeSummary.map((item) => <div key={item.name} className="rounded-lg border border-slate-100 bg-slate-50 p-3"><p className="text-[10px] font-semibold uppercase tracking-wide text-slate-500">{item.name}</p><p className="mt-1 text-xl font-bold text-indigo-700">{item.count}</p><p className="text-[10px] text-slate-400">resource(s)</p></div>)}</div></Card>
    <Card title={`Resource List · ${filtered.length} record(s)`} noPadding><div className="overflow-x-auto"><table className="w-full min-w-[1120px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="px-3 py-3">#</th><th className="px-3 py-3">Resource Name</th><th className="px-3 py-3">Type</th><th className="px-3 py-3">Class & Subject</th><th className="px-3 py-3">Chapters Linked</th><th className="px-3 py-3">Location / URL</th><th className="px-3 py-3">Availability</th><th className="px-3 py-3">Added By</th><th className="px-3 py-3">Status</th><th className="px-3 py-3">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{filtered.map((item, index) => <tr key={item.id} className="hover:bg-slate-50"><td className="px-3 py-3 text-slate-400">{index + 1}</td><td className="px-3 py-3"><p className="font-semibold text-slate-800">{item.name}</p><p className="text-[10px] text-slate-400">{item.shortName} · {item.format}</p></td><td className="px-3 py-3"><Badge variant="info">{item.type}</Badge></td><td className="px-3 py-3">{item.classes.join(', ')}<p className="text-[10px] text-slate-400">{item.subjects}</p></td><td className="max-w-44 px-3 py-3 text-xs">{item.chapters || '—'}</td><td className="max-w-44 break-all px-3 py-3 text-xs">{item.physicalLocation || item.url || '—'}</td><td className="px-3 py-3"><StatusPill status={item.availability} /></td><td className="px-3 py-3 text-xs">{item.addedBy}</td><td className="px-3 py-3"><StatusPill status={item.status} /></td><td className="px-3 py-3"><div className="flex gap-1"><Button size="xs" variant="outline" onClick={() => setForm({ ...item })}><Edit3 className="h-3 w-3" />Edit</Button><Button size="xs" variant="ghost" onClick={() => remove(item)} title="Delete resource"><Trash2 className="h-3.5 w-3.5" /></Button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={10} className="px-4 py-10 text-center text-sm text-slate-400">No resources match these filters.</td></tr>}</tbody></table></div></Card>
    <Modal isOpen={Boolean(form)} onClose={() => setForm(null)} title={form ? `${resources.some((item) => item.id === form.id) ? 'Edit' : 'Add'} Resource` : 'Resource'} size="xl" footer={<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setForm(null)}>Cancel</Button><Button onClick={save}>Save Resource</Button></div>}>
      {form && <div className="max-h-[76vh] space-y-4 overflow-y-auto pr-1"><PlanningPanel title="Panel 1 · Resource Identity"><div className="grid gap-3 md:grid-cols-3"><TextField label="Resource Name" value={form.name} onChange={(value) => update('name', value)} /><TextField label="Short Name" value={form.shortName} onChange={(value) => update('shortName', value)} /><SelectField label="Resource Type" value={form.type} onChange={(value) => update('type', value)} options={RESOURCE_TYPES} /><TextField label="Subject Area(s)" value={form.subjects} onChange={(value) => update('subjects', value)} placeholder="Science, Chemistry" /><TextField label="Author / Publisher" value={form.authorPublisher} onChange={(value) => update('authorPublisher', value)} /><TextField label="Edition / Year" value={form.editionYear} onChange={(value) => update('editionYear', value)} /><SelectField label="Language" value={form.language} onChange={(value) => update('language', value)} options={['English', 'Hindi', 'Regional Language', 'Bilingual']} /></div><div><p className="mb-2 text-xs font-semibold text-slate-600">Applicable Classes</p><div className="grid max-h-32 grid-cols-2 gap-1 overflow-y-auto rounded border border-slate-100 p-2 sm:grid-cols-4">{CLASSES.map((className) => <CheckField key={className} label={className} checked={form.classes.includes(className)} onChange={() => toggleClass(className)} />)}</div></div></PlanningPanel>
        <PlanningPanel title="Panel 2 · Curriculum Mapping"><div><p className="mb-2 text-xs font-semibold text-slate-600">Map chapters from Curriculum Master</p>{mappedChapters.length ? <div className="grid max-h-36 grid-cols-1 gap-1 overflow-y-auto rounded-lg border border-slate-100 p-2 md:grid-cols-2">{mappedChapters.map((chapter) => <CheckField key={chapter.id} label={`${chapter.className} · ${chapter.subject} · Ch ${chapter.chapterNumber}: ${chapter.name}`} checked={form.chapters.split(';').map((name) => name.trim()).includes(chapter.name)} onChange={() => toggleMappedChapter(chapter.name)} />)}</div> : <p className="rounded border border-dashed border-slate-200 p-3 text-xs text-slate-500">Select applicable classes and subject area(s) to show curriculum chapters here.</p>}</div><div className="grid gap-3 md:grid-cols-2"><TextAreaField label="Additional Chapter References" value={form.chapters} onChange={(value) => update('chapters', value)} /><TextAreaField label="Topic(s) Covered" value={form.topics} onChange={(value) => update('topics', value)} /><TextAreaField label="Learning Objectives Supported" value={form.learningObjectives} onChange={(value) => update('learningObjectives', value)} /><SelectField label="Coverage" value={form.coverage} onChange={(value) => update('coverage', value)} options={['Full curriculum', 'Partial coverage — pages / sections specified']} /></div></PlanningPanel>
        <PlanningPanel title="Panel 3 · Access & Availability"><div className="grid gap-3 md:grid-cols-3"><SelectField label="Format" value={form.format} onChange={(value) => update('format', value)} options={['Physical (Book)', 'Digital File', 'Online URL', 'Both']} /><TextField label="Physical Location" value={form.physicalLocation} onChange={(value) => update('physicalLocation', value)} placeholder="Library shelf / lab / department room" /><TextField label="Library Catalog No." value={form.libraryCatalogNo} onChange={(value) => update('libraryCatalogNo', value)} /><TextField label="Number of Copies" type="number" min="0" value={form.copies} onChange={(value) => update('copies', Number(value) || 0)} /><label className="block"><span className="mb-1 block text-xs font-semibold text-slate-600">Digital File · PDF / PPT / DOC / MP4</span><input type="file" className={inputClass} onChange={(event) => update('digitalFile', event.target.files?.[0]?.name || form.digitalFile)} /><span className="mt-1 block text-[10px] text-slate-500">{form.digitalFile || 'No file selected.'}</span></label><TextField label="URL" value={form.url} onChange={(value) => update('url', value)} /><SelectField label="Access Type" value={form.accessType} onChange={(value) => update('accessType', value)} options={['Free', 'Subscription required', 'School-owned']} /><CheckField label="Offline available" checked={form.offlineAvailable} onChange={(checked) => update('offlineAvailable', checked)} /><SelectField label="Availability" value={form.availability} onChange={setAvailability} options={['Available in school', 'Needs to be sourced', 'Online only']} /></div></PlanningPanel>
        <PlanningPanel title="Panel 4 · Usage Recommendation"><div className="grid gap-3 md:grid-cols-3"><SelectField label="Primary / Supplementary" value={form.primarySupplementary} onChange={(value) => update('primarySupplementary', value)} options={['Primary', 'Supplementary']} /><SelectField label="Recommended For" value={form.recommendedFor} onChange={(value) => update('recommendedFor', value)} options={['All students', 'Advanced students', 'Struggling students']} /><SelectField label="When to Use" value={form.whenToUse} onChange={(value) => update('whenToUse', value)} options={['Introduction', 'Practice', 'Revision', 'Enrichment']} /><TextField label="Estimated Time to Use" value={form.estimatedTime} onChange={(value) => update('estimatedTime', value)} placeholder="e.g. 20 minutes / 3 lessons" /><TextAreaField label="Teacher Notes" value={form.teacherNotes} onChange={(value) => update('teacherNotes', value)} /><TextAreaField label="Student Instructions" value={form.studentInstructions} onChange={(value) => update('studentInstructions', value)} /></div></PlanningPanel>
        <PlanningPanel title="Panel 5 · Quality & Review"><div className="grid gap-3 md:grid-cols-3"><TextField label="Teacher Rating · 1–5" type="number" min="0" max="5" value={form.teacherRating} onChange={(value) => update('teacherRating', Math.min(5, Math.max(0, Number(value) || 0)))} /><TextAreaField label="Review Comments" value={form.reviewComments} onChange={(value) => update('reviewComments', value)} /><SelectField label="HOD Approval" value={form.hodApproval} onChange={(value) => update('hodApproval', value)} options={['Yes', 'No', 'Pending']} /><SelectField label="Board Recommended" value={form.boardRecommended} onChange={(value) => update('boardRecommended', value)} options={['No', 'Yes — CBSE', 'Yes — GSEB', 'Yes — CISCE']} /><CheckField label="Aligned with NEP 2020" checked={form.alignedWithNEP} onChange={(checked) => update('alignedWithNEP', checked)} /><CheckField label="Curriculum aligned / verified" checked={form.curriculumAligned} onChange={(checked) => update('curriculumAligned', checked)} /><TextField label="Last Reviewed On" type="date" value={form.lastReviewedOn} onChange={(value) => update('lastReviewedOn', value)} /></div></PlanningPanel>
        <PlanningPanel title="Panel 6 · Administrative"><div className="grid gap-3 md:grid-cols-3"><TextField label="Cost (₹)" type="number" min="0" value={form.cost} onChange={(value) => update('cost', Number(value) || 0)} /><TextField label="Procured Through" value={form.procuredThrough} onChange={(value) => update('procuredThrough', value)} /><SelectField label="Added By" value={form.addedBy} onChange={(value) => update('addedBy', value)} options={['Teacher', 'HOD', 'Admin']} /><SelectField label="Status" value={form.status} onChange={(value) => update('status', value as ResourceRecord['status'])} options={['Active', 'Inactive']} /><CheckField label="Add / keep on procurement wishlist" checked={form.procurementRequested} onChange={(checked) => update('procurementRequested', checked)} /></div></PlanningPanel>
      </div>}
    </Modal>
  </div>;
}
