import React, { useMemo, useState } from 'react';
import { BarChart3, Calendar, CheckCircle2, Clock3, Download, Eye, FileText, Layers, ListFilter, ShieldCheck, X } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Input } from '../../../components/ui/Input';
import { Modal } from '../../../components/ui/Modal';
import { Select } from '../../../components/ui/Select';
import { Table } from '../../../components/ui/Table';

type ReportFormat = 'pdf' | 'excel' | 'csv';
type ReportStatus = 'Ready' | 'Scheduled';
type ReportDefinition = { id: string; number: number; name: string; description: string };
type ReportCategory = { id: string; label: string; description: string; reports: ReportDefinition[] };
type ReportCategorySeed = { id: string; label: string; description: string; reports: Array<[string, string]> };
type ReportRow = {
  id: string;
  reportNumber: number;
  name: string;
  generatedBy: string;
  date: string;
  format: string;
  size: string;
  category: string;
  period: string;
  description: string;
  status: ReportStatus;
};

const CATEGORY_SEEDS: ReportCategorySeed[] = [
  {
    id: 'user-access', label: 'CATEGORY 1: USER & ACCESS REPORTS',
    description: 'Reports about who uses the ERP, how they access it, and their activity.',
    reports: [
      ['User Login History Report', 'Every login — who, when, from which device/browser/IP.'],
      ['User Logout History Report', 'Every logout — timestamp and session duration.'],
      ['Failed Login Attempts Report', 'All failed logins — potential security issue, wrong passwords.'],
      ['Active Users Report', 'Users who logged in within a selected date range.'],
      ['Inactive Users Report', 'Users who have NOT logged in for X days — accounts may need deactivation.'],
      ['Concurrent Users Report', 'How many users were logged in at the same time — peak usage times.'],
      ['User Session Duration Report', 'How long each user stays logged in per session.'],
      ['First Login Report', 'When each user logged in for the very first time.'],
      ['Last Login Report', 'Last time each user was active — sorted by most recent.'],
      ['Password Reset History Report', 'All password reset requests and completions — who, when.'],
      ['Login by Device/Browser Report', 'What devices and browsers users are using.'],
      ['Login by IP Address Report', 'All logins grouped by IP — detect unusual locations.'],
      ['Multi-Device Login Report', 'Users logged in from more than one device simultaneously.'],
      ['After-Hours Login Report', 'Logins that happened outside school working hours.'],
      ['Account Locked Report', 'Accounts locked due to too many failed login attempts.'],
      ['New User Created Report', 'All new user accounts created in a date range.'],
      ['User Deactivated Report', 'Accounts deactivated — when and by whom.'],
      ['User Role Change Report', "When a user's role was changed — old role to new role."],
      ['User Permission Change Report', 'Changes made to what a user can access.'],
      ['Guest / Temporary Account Report', 'Temporary accounts created — status and expiry.']
    ]
  },
  {
    id: 'security', label: 'CATEGORY 2: SECURITY REPORTS',
    description: 'Reports about system security events and threats.',
    reports: [
      ['Security Alerts Report', 'All security alerts generated by the system.'],
      ['Unauthorized Access Attempt Report', 'Attempts to access pages/modules without permission.'],
      ['Suspicious Activity Report', 'Flagged unusual behavior — bulk downloads, odd hours access.'],
      ['IP Blacklist Report', 'IPs that have been blocked from accessing ERP.'],
      ['Privilege Escalation Attempt Report', 'Attempts by users to access higher-level functions.'],
      ['Data Export by User Report', 'Who exported what data — when and how much.'],
      ['Bulk Action Report', 'All bulk operations performed — bulk approve, bulk delete, bulk export.'],
      ['Sensitive Data Access Report', 'Who accessed sensitive records — salary, medical, Aadhaar data.'],
      ['Session Timeout Report', 'Sessions that auto-expired due to inactivity.'],
      ['Two-Factor Authentication (2FA) Report', '2FA usage — who has it enabled, recent verifications.'],
      ['API Access Report', 'All API calls made to ERP — third-party integrations.'],
      ['API Error Report', 'Failed API calls — error codes and frequency.'],
      ['Token Expiry Report', 'Authentication tokens that expired or were revoked.'],
      ['SSL Certificate Status Report', 'SSL certificate validity and expiry dates.']
    ]
  },
  {
    id: 'system-performance', label: 'CATEGORY 3: SYSTEM PERFORMANCE REPORTS',
    description: 'Reports about how the ERP system is performing technically.',
    reports: [
      ['System Uptime Report', 'How long the ERP has been running without downtime.'],
      ['System Downtime Report', 'When the system was down — duration and reason.'],
      ['Page Load Time Report', 'How fast each page loads — identify slow pages.'],
      ['Slow Query Report', 'Database queries that took too long — performance bottlenecks.'],
      ['API Response Time Report', 'How fast each API endpoint responds.'],
      ['Server CPU Usage Report', 'CPU utilization over time — peak load periods.'],
      ['Server Memory (RAM) Usage Report', 'RAM consumption trends — out of memory risks.'],
      ['Server Disk I/O Report', 'Disk read/write activity — storage performance.'],
      ['Network Bandwidth Report', 'Data transferred in/out of ERP — bandwidth usage.'],
      ['Database Performance Report', 'Database response times, query counts, connection pool usage.'],
      ['Database Size Growth Report', 'How fast the database is growing — storage planning.'],
      ['Cache Hit/Miss Report', 'How effectively the caching layer is working.'],
      ['Background Job Performance Report', 'How fast background tasks (archiving, email) complete.'],
      ['Peak Usage Hours Report', 'Which hours have most user activity — server planning.'],
      ['System Health Check Report', 'Overall health — all green/warning/critical indicators.'],
      ['CDN Performance Report', 'Content delivery network performance for files/images.']
    ]
  },
  {
    id: 'errors-exceptions', label: 'CATEGORY 4: ERROR & EXCEPTION REPORTS',
    description: 'Reports about errors, failures, and exceptions in the ERP.',
    reports: [
      ['System Error Log Report', 'All system errors with error codes and stack traces.'],
      ['Application Error Report', 'Errors that occurred within the ERP application.'],
      ['Database Error Report', 'Database connection failures, query errors.'],
      ['Unhandled Exception Report', 'Crashes or unhandled errors — needs developer attention.'],
      ['404 / Page Not Found Report', "Pages users tried to access that don't exist."],
      ['500 / Server Error Report', 'Internal server errors — frequency and context.'],
      ['Form Validation Error Report', 'Most common form submission errors — UX improvement.'],
      ['File Upload Error Report', 'Failed file uploads — size issues, format issues.'],
      ['Payment Gateway Error Report', 'Failed online payment processing attempts.'],
      ['Email Delivery Failure Report', 'Emails that failed to send — which addresses, when.'],
      ['SMS Delivery Failure Report', 'SMS notifications that failed to deliver.'],
      ['Print / PDF Generation Error Report', 'Failed receipt / document generation attempts.'],
      ['Import Error Report', 'Data imports that failed — which file, which rows failed.'],
      ['Export Error Report', 'Data exports that failed to generate.'],
      ['Integration Error Report', 'Failures in third-party system connections (bank, portal).'],
      ['Scheduled Job Failure Report', 'Automated jobs that failed to run (archiving, backups).'],
      ['Timeout Error Report', 'Operations that timed out — server overload indicators.']
    ]
  },
  {
    id: 'module-usage', label: 'CATEGORY 5: MODULE USAGE REPORTS',
    description: 'Reports about how each module of the ERP is being used.',
    reports: [
      ['Module Usage Frequency Report', 'Which modules are used most/least — daily/weekly/monthly.'],
      ['Page Visit Report', 'Which pages are visited most — heatmap of usage.'],
      ['Feature Usage Report', 'Which features/buttons are clicked most.'],
      ['Module Login Count Report', 'How many times each module is accessed per user.'],
      ['Unused Module Report', 'Modules that have never been accessed or rarely used.'],
      ['Most Active Module Report', 'Modules with highest transaction volume.'],
      ['Module-wise User Activity Report', 'Which users are most active in which modules.'],
      ['Report Generation Frequency Report', 'Which ERP reports are generated most often.'],
      ['Search Query Report', 'What users search for most — UX insights.'],
      ['Filter Usage Report', 'Which filters users apply most — common patterns.'],
      ['Form Completion Rate Report', 'How many started forms are completed vs abandoned.'],
      ['Module Adoption Report', "After a new module launch — who is using it and who isn't."],
      ['Mobile vs Desktop Usage Report', 'How many users access ERP from mobile vs desktop.'],
      ['Browser Usage Report', 'Which browsers users use — compatibility planning.']
    ]
  },
  {
    id: 'workflow-approvals', label: 'CATEGORY 6: WORKFLOW & APPROVAL SYSTEM REPORTS',
    description: 'Reports about the approval workflow system itself.',
    reports: [
      ['Workflow Configuration Report', 'All configured approval workflows — their settings.'],
      ['Workflow Usage Report', 'How many times each workflow was triggered.'],
      ['Approval TAT (Turnaround Time) Report', 'Average time taken to approve items per workflow.'],
      ['SLA Compliance Report', 'What % of approvals completed within SLA time.'],
      ['SLA Breach Report', 'All approvals that exceeded SLA time — who, when, how long.'],
      ['Approver Workload Report', 'How many approvals each approver handled.'],
      ['Approver Response Time Report', 'How fast each approver responds to requests.'],
      ['Escalation Report', 'All items that were escalated — reason and outcome.'],
      ['Auto-Approval Report', 'Items auto-approved by system rules — count and values.'],
      ['Auto-Rejection Report', 'Items auto-rejected by system rules.'],
      ['Delegation Usage Report', 'How often approval delegation was used.'],
      ['Pending Approvals Aging Report', 'Items waiting for approval — sorted by how long waiting.'],
      ['Rejection Reason Analysis Report', 'Most common reasons for rejection across all workflows.'],
      ['Bottleneck Identification Report', 'Which approver or stage causes most delays.'],
      ['Workflow Change History Report', 'Changes made to workflow configurations — when and by whom.']
    ]
  },
  {
    id: 'data-lock-override', label: 'CATEGORY 7: DATA LOCK & OVERRIDE REPORTS',
    description: 'Reports about the data locking system.',
    reports: [
      ['Module Lock Status Report', 'Current lock status of all modules — locked/unlocked.'],
      ['Lock History Report', 'All lock and unlock events — who, when, which module.'],
      ['Override Request Report', 'All override requests — approved, denied, pending.'],
      ['Override Usage Report', 'How often overrides are granted per module.'],
      ['Override Duration Report', 'How long overrides ran — within time or extended.'],
      ['Frequent Override Requesters Report', 'Which users request overrides most — may indicate issues.'],
      ['Lock Violation Attempt Report', 'Attempts to edit locked data — who tried, what module.'],
      ['Override Persons List Report', 'Current list of people approved for override access.'],
      ['Auto-Relock Confirmation Report', 'Confirmation that auto-relock happened after timer expired.'],
      ['Override Revocation Report', 'Overrides that were manually revoked before timer ended.']
    ]
  },
  {
    id: 'storage-archive', label: 'CATEGORY 8: STORAGE & ARCHIVE REPORTS',
    description: 'Reports about data storage, archiving, and cold storage.',
    reports: [
      ['Total Storage Usage Report', 'How much storage is being used across all tiers.'],
      ['Storage Growth Trend Report', 'How storage has grown over months — projection.'],
      ['Primary Database Size Report', 'Current primary DB size per module.'],
      ['Archive Database Size Report', 'Current archive DB size per module.'],
      ['Cold Storage Size Report', 'Files in cold storage — sizes and costs.'],
      ['Module-wise Storage Report', 'Which module is using how much storage.'],
      ['Storage Cost Report', 'Monthly storage costs broken down by tier and module.'],
      ['Storage Savings Report', 'How much money archiving has saved vs no archiving.'],
      ['Archive Job History Report', 'All archive jobs run — success, failure, records moved.'],
      ['Archive Job Failure Report', 'Archive jobs that failed — reason and retry status.'],
      ['Cold Storage Push Report', 'All cold storage push operations — files, sizes, costs.'],
      ['Cold Storage Retrieval Report', 'All retrievals from cold storage — who, when, cost, reason.'],
      ['Retrieval Cost Report', 'Total cost of cold storage retrievals over time.'],
      ['Data Eligible for Deletion Report', 'Data that has met its retention period and can be deleted.'],
      ['Data Retention Compliance Report', 'Is all data being retained for the correct legal period.'],
      ['Deletion Certificate Report', 'All data permanently deleted — certificates and details.'],
      ['Backup Status Report', 'All backup operations — success, failure, size, duration.'],
      ['Backup Storage Report', 'How much space backups are consuming.'],
      ['Backup Frequency Report', 'Whether backups are running on schedule.'],
      ['Compression Ratio Report', 'How much compression is saving in archive/cold storage.'],
      ['Temp File Cleanup Report', 'Temp files cleaned up — size recovered.'],
      ['Image/Document Optimization Report', 'Space saved from compressing images and documents.']
    ]
  },
  {
    id: 'number-series', label: 'CATEGORY 9: NUMBER SERIES REPORTS',
    description: 'Reports about the number series configuration and usage.',
    reports: [
      ['Number Series Configuration Report', 'All configured number series — their formats and settings.'],
      ['Number Series Usage Report', 'How many numbers each series has generated.'],
      ['Numbers Generated Per Day Report', 'Daily count of numbers generated per series.'],
      ['Number Series Near Capacity Report', 'Series approaching their maximum number.'],
      ['Number Series Reset History Report', 'All counter resets — when, why, from/to values.'],
      ['Manual Counter Reset Report', 'Resets done manually by admin — with justification.'],
      ['Inactive Number Series Report', 'Series configured but never used or used very rarely.'],
      ['Number Gap Report', 'Gaps in sequence (deleted records) — sequence number, record.'],
      ['Duplicate Number Alert Report', 'Any duplicate numbers found (should be zero — alerts).'],
      ['Series Auto-Reset Confirmation Report', 'Confirmation that scheduled resets happened correctly.']
    ]
  },
  {
    id: 'notifications', label: 'CATEGORY 10: NOTIFICATION & COMMUNICATION REPORTS',
    description: 'Reports about system notifications sent to users.',
    reports: [
      ['Notification Sent Report', 'All notifications sent — type, recipient, channel, time.'],
      ['Email Delivery Report', 'Emails sent — delivered, bounced, opened.'],
      ['SMS Delivery Report', 'SMS sent — delivered, failed, pending.'],
      ['Push Notification Report', 'App push notifications sent and their delivery status.'],
      ['WhatsApp Message Report', 'WhatsApp messages sent (if integrated).'],
      ['Notification Failure Report', 'Notifications that failed to deliver — with error.'],
      ['Unsubscribed Users Report', 'Users who unsubscribed from ERP notifications.'],
      ['Notification Volume Report', 'How many notifications sent per day/week/month.'],
      ['Notification Type Breakdown Report', 'Which types of notifications are sent most.'],
      ['Email Bounce Report', 'Invalid email addresses causing bounces.'],
      ['SMS Credit Balance Report', 'Remaining SMS credits — when to recharge.'],
      ['Notification Delivery Rate Report', 'Success rate of notification delivery.']
    ]
  },
  {
    id: 'configuration-settings', label: 'CATEGORY 11: CONFIGURATION & SETTINGS REPORTS',
    description: 'Reports about how the ERP is configured.',
    reports: [
      ['System Configuration Report', 'All current system settings in one report.'],
      ['Configuration Change History Report', 'Every time a setting was changed — who, when, old vs new value.'],
      ['User Role Configuration Report', 'All roles and their permission sets.'],
      ['Role Change History Report', 'Changes made to role permissions over time.'],
      ['Module Configuration Report', 'Configuration settings for each module.'],
      ['Financial Year Configuration Report', 'All financial years — open, closed, dates.'],
      ['Academic Year Configuration Report', 'Academic year setup and structure.'],
      ['Fee Structure Configuration Report', 'All fee structures defined in system.'],
      ['Approval Workflow Configuration Report', 'All workflows — levels, approvers, SLA settings.'],
      ['Archive Configuration Report', 'Retention policies configured for each module.'],
      ['Number Series Configuration Report', 'All series — format, reset type, current counter.'],
      ['Integration Configuration Report', 'All third-party integrations — payment gateways, SMS, etc.'],
      ['Bank Account Configuration Report', 'School bank accounts configured in ERP.'],
      ['Chart of Accounts Report', 'All accounts in the account master.'],
      ['Tax Configuration Report', 'GST rates, TDS rates configured in system.'],
      ['School Profile Configuration Report', 'School details, branch details, CBSE info.']
    ]
  },
  {
    id: 'audit-trail', label: 'CATEGORY 12: AUDIT TRAIL REPORTS',
    description: 'Reports from the complete audit trail of the ERP.',
    reports: [
      ['Complete Audit Trail Report', 'Every action ever taken in the ERP — who did what when.'],
      ['Module-wise Audit Report', 'Audit trail filtered by specific module.'],
      ['User-wise Audit Report', 'All actions performed by a specific user.'],
      ['Record-wise Audit Report', 'All changes made to a specific record.'],
      ['Data Creation Report', 'All records created — who created what, when.'],
      ['Data Modification Report', 'All records edited — old value vs new value.'],
      ['Data Deletion Report', 'All records deleted — who deleted, when, what.'],
      ['Before & After Change Report', 'Specific records — original value and current value.'],
      ['Critical Action Report', 'High-risk actions — bulk deletes, financial approvals, unlocks.'],
      ['Approval Audit Report', 'All approval decisions — approved, rejected, with remarks.'],
      ['Financial Transaction Audit Report', 'All financial entry actions — create, approve, reverse.'],
      ['Period Lock/Unlock Audit Report', 'All period locking and unlocking events.'],
      ['Data Export Audit Report', 'Every time data was exported — who, what, when.'],
      ['Print Audit Report', 'Every time something was printed from ERP.']
    ]
  },
  {
    id: 'integration-sync', label: 'CATEGORY 13: INTEGRATION & SYNC REPORTS',
    description: 'Reports about external integrations and data syncing.',
    reports: [
      ['Payment Gateway Transaction Report', 'All payment gateway calls — success, failure, amounts.'],
      ['Payment Gateway Reconciliation Report', 'ERP payment records vs gateway settlement.'],
      ['Bank Integration Report', 'Bank API calls — balance checks, transfers.'],
      ['SMS Gateway Report', 'SMS gateway usage — messages sent, credits used.'],
      ['Email Gateway Report', 'Email gateway usage — emails sent, bounces.'],
      ['Government Portal Sync Report', 'NSP, UDISE, Board portal sync status.'],
      ['Biometric Device Sync Report', 'Biometric punch data sync — success/failure per device.'],
      ['RFID Sync Report', 'RFID data sync from physical devices.'],
      ['API Rate Limit Report', 'API calls approaching or hitting rate limits.'],
      ['Webhook Delivery Report', 'Outgoing webhooks — delivered, failed, retried.'],
      ['Data Import Report', 'All bulk data imports — file, records, success/failure count.'],
      ['Data Export Schedule Report', 'Scheduled exports — status and completion.'],
      ['Third-Party Connector Report', 'Status of all connected third-party services.'],
      ['Integration Health Report', 'Overall health of all integrations at a glance.']
    ]
  },
  {
    id: 'scheduled-jobs', label: 'CATEGORY 14: SCHEDULED JOBS & AUTOMATION REPORTS',
    description: 'Reports about automated background tasks.',
    reports: [
      ['Scheduled Jobs Status Report', 'All scheduled jobs — last run, next run, status.'],
      ['Job Execution History Report', 'Every time a job ran — duration, records processed, status.'],
      ['Job Failure Report', 'Jobs that failed — error message, attempts, retry status.'],
      ['Job Performance Report', 'How long each job takes to run — optimization target.'],
      ['Archive Job Report', 'All archive automation runs — records moved, space freed.'],
      ['Backup Job Report', 'All backup jobs — success, failure, size, duration.'],
      ['Cleanup Job Report', 'Temp file and log cleanup jobs — space recovered.'],
      ['Cold Storage Push Job Report', 'All cold storage automation runs.'],
      ['Email Job Queue Report', 'Emails queued for sending — pending, sent, failed.'],
      ['SMS Job Queue Report', 'SMS queued for delivery — pending, sent, failed.'],
      ['Notification Job Report', 'All notification batch jobs — sent count, failed count.'],
      ['Auto-Approval Job Report', 'Items auto-approved by scheduled system rules.'],
      ['Period Close Job Report', 'Automated period closing runs.'],
      ['Number Series Reset Job Report', 'Automated counter resets — which series, when.']
    ]
  },
  {
    id: 'user-management', label: 'CATEGORY 15: USER MANAGEMENT REPORTS',
    description: 'Reports about user accounts and role management.',
    reports: [
      ['All Users List Report', 'Complete list of all ERP user accounts.'],
      ['Users by Role Report', 'Users grouped by their assigned role.'],
      ['Users by Module Access Report', 'Who has access to which modules.'],
      ['Super Admin Users Report', 'All users with Super Admin privileges.'],
      ['Shared Account Report', 'Accounts that appear to be shared (multiple IPs, unusual patterns).'],
      ['Orphan User Report', 'ERP accounts of staff who have left the school.'],
      ['User Account Age Report', 'How old each account is — old accounts may need review.'],
      ['User Activity Score Report', 'Ranked list of users by how active they are.'],
      ['Zero-Activity User Report', 'Users with accounts but no activity whatsoever.'],
      ['Role Mismatch Report', "Users with a role that doesn't match their designation."]
    ]
  },
  {
    id: 'system-health-compliance', label: 'CATEGORY 16: SYSTEM HEALTH & COMPLIANCE REPORTS',
    description: 'Overall system health and ERP compliance reports.',
    reports: [
      ['Overall System Health Report', 'Single page — all system health metrics combined.'],
      ['Daily System Summary Report', "Auto-generated every morning — yesterday's system activity."],
      ['Weekly System Report', "Week's summary — usage, errors, performance."],
      ['Monthly System Report', 'Monthly ERP performance and usage summary.'],
      ['Annual ERP Usage Report', 'Full year summary of ERP usage and performance.'],
      ['Compliance Checklist Report', 'Is the ERP configured correctly for all compliance needs.'],
      ['Data Retention Compliance Report', 'Is data being kept/deleted per legal retention rules.'],
      ['User Access Compliance Report', 'Are user permissions correctly set per their roles.'],
      ['Password Policy Compliance Report', 'Are users following password policies.'],
      ['2FA Adoption Report', 'What % of users have 2FA enabled.'],
      ['ERP License Usage Report', 'How many user licenses are used vs total purchased.'],
      ['Feature Utilization Report', 'Which ERP features are used and which are ignored.'],
      ['Support Ticket Report', 'Issues raised about ERP — resolved, pending, common problems.'],
      ['ERP Version & Patch Report', 'Current ERP version, patches applied, pending updates.'],
      ['Module Activation Report', 'Which modules are activated/deactivated.'],
      ['System Availability SLA Report', 'Uptime vs agreed SLA — is ERP meeting availability targets.']
    ]
  }
];

let nextReportNumber = 1;
const REPORT_CATEGORIES: ReportCategory[] = CATEGORY_SEEDS.map((category) => ({
  ...category,
  reports: category.reports.map(([name, description]) => {
    const report = { id: `report-${nextReportNumber}`, number: nextReportNumber, name, description };
    nextReportNumber += 1;
    return report;
  })
}));
const TOTAL_REPORT_TEMPLATES = REPORT_CATEGORIES.reduce((count, category) => count + category.reports.length, 0);

type ReportFormatOption = { value: ReportFormat; label: string };
const FORMAT_OPTIONS: ReportFormatOption[] = [
  { value: 'pdf', label: 'PDF Document' },
  { value: 'excel', label: 'Excel Spreadsheet' },
  { value: 'csv', label: 'CSV File' }
];
const FORMAT_LABEL: Record<ReportFormat, string> = { pdf: 'PDF', excel: 'Excel', csv: 'CSV' };
const displayDate = (date: Date) => date.toLocaleDateString('en-GB', { day: '2-digit', month: 'short', year: 'numeric' }).replace(/ /g, '-');
const estimateSize = (format: ReportFormat) => format === 'pdf' ? '850 KB' : format === 'excel' ? '420 KB' : '140 KB';

const reportByNumber = (number: number) => {
  for (const category of REPORT_CATEGORIES) {
    const report = category.reports.find((item) => item.number === number);
    if (report) return { category, report };
  }
  return null;
};

const makeInitialReport = (number: number, generatedBy: string, date: string, format: string, size: string, period: string): ReportRow => {
  const match = reportByNumber(number);
  if (!match) throw new Error(`Missing report template #${number}`);
  return {
    id: `seed-${number}`,
    reportNumber: number,
    name: match.report.name,
    generatedBy,
    date,
    format,
    size,
    category: match.category.label,
    period,
    description: match.report.description,
    status: 'Ready'
  };
};

const INITIAL_REPORTS: ReportRow[] = [
  makeInitialReport(1, 'System', '02-Oct-2026', 'PDF', '1.2 MB', '01-Sep-2026 to 30-Sep-2026'),
  makeInitialReport(21, 'Admin', '01-Oct-2026', 'Excel', '450 KB', '01-Sep-2026 to 30-Sep-2026'),
  makeInitialReport(49, 'Principal', '30-Sep-2026', 'CSV', '120 KB', '01-Sep-2026 to 30-Sep-2026'),
  makeInitialReport(219, 'System', '26-Sep-2026', 'PDF', '2.5 MB', '01-Jul-2026 to 25-Sep-2026')
];

const buildReportPreviewRows = (report: ReportRow) => {
  const id = `ACR-${String(report.reportNumber).padStart(3, '0')}`;
  return [
    { recordId: `${id}-001`, entity: 'Main Campus · Academic Operations', result: 'Complete', measure: '1,284 records' },
    { recordId: `${id}-002`, entity: 'North Campus · User & Access Activity', result: 'Review', measure: '18 flagged items' },
    { recordId: `${id}-003`, entity: 'School-wide · Compliance Summary', result: 'Complete', measure: '98.6% coverage' }
  ];
};

export function AdministrativeControlReports() {
  const [categoryId, setCategoryId] = useState('');
  const [reportId, setReportId] = useState('');
  const [format, setFormat] = useState<ReportFormat>('pdf');
  const [fromDate, setFromDate] = useState('');
  const [toDate, setToDate] = useState('');
  const [reports, setReports] = useState(INITIAL_REPORTS);
  const [selectedReport, setSelectedReport] = useState<ReportRow | null>(null);
  const [scheduleOpen, setScheduleOpen] = useState(false);
  const [scheduleFrequency, setScheduleFrequency] = useState('Weekly');
  const [toast, setToast] = useState('');

  const selectedCategory = REPORT_CATEGORIES.find((category) => category.id === categoryId);
  const selectedTemplate = selectedCategory?.reports.find((report) => report.id === reportId);
  const invalidDateRange = Boolean(fromDate && toDate && fromDate > toDate);
  const reportPeriod = fromDate || toDate ? `${fromDate || 'Start'} to ${toDate || 'Today'}` : 'All available dates';
  const categoryOptions = useMemo(() => [
    { value: '', label: 'Choose a report category' },
    ...REPORT_CATEGORIES.map((category) => ({ value: category.id, label: category.label }))
  ], []);
  const reportOptions = selectedCategory
    ? [{ value: '', label: 'Choose a report' }, ...selectedCategory.reports.map((report) => ({ value: report.id, label: `${report.number}. ${report.name}` }))]
    : [{ value: '', label: 'Choose a category above first' }];

  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3000); };

  const generateReport = () => {
    if (!selectedCategory || !selectedTemplate) { notify('Choose a category and report to continue.'); return; }
    if (invalidDateRange) { notify('The From Date must be earlier than the To Date.'); return; }
    const newReport: ReportRow = {
      id: `RPT-${Date.now()}`,
      reportNumber: selectedTemplate.number,
      name: selectedTemplate.name,
      generatedBy: 'Current User',
      date: displayDate(new Date()),
      format: FORMAT_LABEL[format],
      size: estimateSize(format),
      category: selectedCategory.label,
      period: reportPeriod,
      description: selectedTemplate.description,
      status: 'Ready'
    };
    setReports((current) => [newReport, ...current]);
    notify(`${newReport.name} created in this frontend preview.`);
  };

  const exportReportList = () => {
    const rows = [
      ['#', 'Report Name', 'Category', 'Generated By', 'Date', 'Period', 'Format', 'Size', 'Status'],
      ...reports.map((report) => [report.reportNumber, report.name, report.category, report.generatedBy, report.date, report.period, report.format, report.size, report.status])
    ];
    const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n');
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    link.download = 'administrative-control-reports.csv';
    link.click();
    window.setTimeout(() => URL.revokeObjectURL(link.href), 0);
    notify('Report register exported as CSV.');
  };

  const downloadReportSummary = (report: ReportRow) => {
    const previewRows = buildReportPreviewRows(report);
    const rows = [
      ['Report', report.name],
      ['Category', report.category],
      ['Period', report.period],
      [],
      ['Record ID', 'Entity / Scope', 'Result', 'Measure'],
      ...previewRows.map((row) => [row.recordId, row.entity, row.result, row.measure])
    ];
    const csv = rows.map((row) => row.map((value) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n');
    const link = document.createElement('a');
    link.href = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' }));
    link.download = `${report.name.toLowerCase().replace(/[^a-z0-9]+/g, '-')}-preview.csv`;
    link.click();
    window.setTimeout(() => URL.revokeObjectURL(link.href), 0);
    notify('Report data preview downloaded as CSV.');
  };

  const openSchedule = () => {
    if (!selectedCategory || !selectedTemplate) { notify('Choose a category and report before scheduling.'); return; }
    if (invalidDateRange) { notify('The From Date must be earlier than the To Date.'); return; }
    setScheduleOpen(true);
  };

  const saveSchedule = () => {
    if (!selectedCategory || !selectedTemplate) return;
    const scheduledReport: ReportRow = {
      id: `SCH-${Date.now()}`,
      reportNumber: selectedTemplate.number,
      name: selectedTemplate.name,
      generatedBy: 'Current User',
      date: displayDate(new Date()),
      format: FORMAT_LABEL[format],
      size: '—',
      category: selectedCategory.label,
      period: `${scheduleFrequency} · ${reportPeriod}`,
      description: selectedTemplate.description,
      status: 'Scheduled'
    };
    setReports((current) => [scheduledReport, ...current]);
    setScheduleOpen(false);
    notify(`${scheduleFrequency} schedule added in this frontend preview.`);
  };

  const columns = [
    { key: 'name', header: 'Report Name', render: (row: ReportRow) => <div><span className="font-medium text-slate-800">{row.name}</span><span className="mt-1 block text-[11px] text-slate-400">#{row.reportNumber}</span></div> },
    { key: 'category', header: 'Category', render: (row: ReportRow) => <span className="text-xs text-slate-600">{row.category.replace(/^CATEGORY \d+: /, '')}</span> },
    { key: 'generatedBy', header: 'Generated By' },
    { key: 'date', header: 'Date' },
    { key: 'format', header: 'Format', render: (row: ReportRow) => <Badge variant={row.status === 'Scheduled' ? 'warning' : 'secondary'}>{row.status === 'Scheduled' ? 'Scheduled' : row.format}</Badge> },
    { key: 'size', header: 'Size' },
    { key: 'actions', header: 'Actions', render: (row: ReportRow) => <div className="flex items-center gap-1"><Button variant="ghost" size="xs" onClick={() => setSelectedReport(row)}><Eye className="h-3.5 w-3.5" /> View</Button><Button variant="ghost" size="xs" onClick={() => downloadReportSummary(row)} disabled={row.status === 'Scheduled'}><Download className="h-3.5 w-3.5" /> Data CSV</Button></div> }
  ];

  return (
    <div className="min-h-full space-y-6 bg-slate-50 p-4 md:p-6">
      <div className="flex flex-col justify-between gap-4 md:flex-row md:items-center">
        <div>
          <div className="mb-1 text-xs text-slate-500">Administration / <span className="text-indigo-700">Administrative Control Reports</span></div>
          <h1 className="text-2xl font-bold text-slate-900">Administrative Control Reports</h1>
          <p className="mt-1 text-sm text-slate-500">Choose a report category first, then select one of its reports to configure a preview or schedule.</p>
        </div>
        <Button variant="outline" leftIcon={<Download className="h-4 w-4" />} onClick={exportReportList}>Export report register</Button>
      </div>

      <div className="grid grid-cols-1 gap-4 sm:grid-cols-3">
        <Card className="p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-indigo-50 p-2.5 text-indigo-700"><ListFilter className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">Report categories</p><p className="text-xl font-semibold text-slate-900">{REPORT_CATEGORIES.length}</p></div></div></Card>
        <Card className="p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-blue-50 p-2.5 text-blue-700"><FileText className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">Available report templates</p><p className="text-xl font-semibold text-slate-900">{TOTAL_REPORT_TEMPLATES}</p></div></div></Card>
        <Card className="p-4"><div className="flex items-center gap-3"><span className="rounded-lg bg-emerald-50 p-2.5 text-emerald-700"><BarChart3 className="h-5 w-5" /></span><div><p className="text-xs text-slate-500">Generated / scheduled locally</p><p className="text-xl font-semibold text-slate-900">{reports.length}</p></div></div></Card>
      </div>

      <div className="grid grid-cols-1 gap-6 xl:grid-cols-3">
        <Card title="Quick Report Generation" className="xl:col-span-1">
          <div className="space-y-4">
            <Select
              label="Report Category"
              value={categoryId}
              onChange={(value: string) => { setCategoryId(value); setReportId(''); }}
              options={categoryOptions}
            />
            <Select
              label="Reports"
              value={reportId}
              onChange={(value: string) => setReportId(value)}
              options={reportOptions}
            />
            <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">
              <Input type="date" label="From Date" value={fromDate} onChange={(event) => setFromDate(event.target.value)} />
              <Input type="date" label="To Date" value={toDate} onChange={(event) => setToDate(event.target.value)} />
            </div>
            {invalidDateRange && <p className="text-xs text-red-600">From Date must be earlier than To Date.</p>}
            <Select label="Format" value={format} onChange={(value: string) => setFormat(value as ReportFormat)} options={FORMAT_OPTIONS} />
            <div className="rounded-lg border border-indigo-100 bg-indigo-50 p-3 text-xs leading-relaxed text-indigo-900">
              {selectedTemplate ? <><Layers className="mr-1 inline h-3.5 w-3.5" />{selectedTemplate.description}</> : selectedCategory ? <><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />{selectedCategory.description} Select a report below to preview its details.</> : <><Layers className="mr-1 inline h-3.5 w-3.5" />Select a category, then choose a report from that category.</>}
            </div>
            <div className="flex flex-col gap-2 pt-1 sm:flex-row">
              <Button onClick={generateReport} className="flex-1" disabled={!selectedTemplate || invalidDateRange}><FileText className="h-4 w-4" /> Generate Report</Button>
              <Button variant="outline" onClick={openSchedule} className="flex-1" disabled={!selectedTemplate || invalidDateRange}><Calendar className="h-4 w-4" /> Schedule</Button>
            </div>
          </div>
        </Card>

        <Card title="Recent Reports" className="overflow-hidden xl:col-span-2" headerAction={<Badge variant="info">{reports.length} reports</Badge>}>
          <Table columns={columns} data={reports} emptyMessage="No reports have been generated yet." />
        </Card>
      </div>

      <div className="flex flex-wrap items-center justify-between gap-3 rounded-lg border border-slate-200 bg-white px-4 py-3 text-xs text-slate-500">
        <span><Clock3 className="mr-1 inline h-3.5 w-3.5 text-slate-400" />Report generation shown as a frontend preview; no live ERP data source is connected.</span>
        <span className="flex items-center gap-1"><CheckCircle2 className="h-3.5 w-3.5 text-emerald-600" />View shows sample report rows and key measures for the selected period.</span>
      </div>

      <Modal isOpen={Boolean(selectedReport)} onClose={() => setSelectedReport(null)} title={selectedReport?.name || 'Report preview'} size="lg" footer={selectedReport ? <div className="flex justify-end gap-2"><Button variant="outline" onClick={() => downloadReportSummary(selectedReport)}><Download className="h-4 w-4" /> Download data CSV</Button><Button onClick={() => setSelectedReport(null)}>Close</Button></div> : null}>
        {selectedReport && <div className="space-y-4">
          <div className="flex flex-wrap gap-2"><Badge variant={selectedReport.status === 'Scheduled' ? 'warning' : 'success'}>{selectedReport.status}</Badge><Badge variant="outline">#{selectedReport.reportNumber}</Badge><Badge variant="secondary">{selectedReport.category.replace(/^CATEGORY \d+: /, '')}</Badge></div>
          <p className="text-sm leading-relaxed text-slate-600">{selectedReport.description}</p>
          <div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-4">
            <div><p className="text-xs text-slate-400">Reporting period</p><p className="mt-1 font-medium text-slate-800">{selectedReport.period}</p></div>
            <div><p className="text-xs text-slate-400">Output format</p><p className="mt-1 font-medium text-slate-800">{selectedReport.format}</p></div>
            <div><p className="text-xs text-slate-400">Records in scope</p><p className="mt-1 font-medium text-slate-800">1,284</p></div>
            <div><p className="text-xs text-slate-400">Items flagged</p><p className="mt-1 font-medium text-amber-700">18</p></div>
          </div>
          <section className="overflow-hidden rounded-xl border border-slate-200">
            <div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 bg-slate-50 px-4 py-3"><div><h3 className="text-sm font-semibold text-slate-900">Report data preview</h3><p className="mt-0.5 text-xs text-slate-500">{selectedReport.name} · {selectedReport.period}</p></div><Badge variant="info">3 sample rows</Badge></div>
            <div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="bg-white text-[10px] uppercase tracking-wide text-slate-500"><tr><th className="p-3">Record ID</th><th className="p-3">Entity / Scope</th><th className="p-3">Result</th><th className="p-3">Measure</th></tr></thead><tbody className="divide-y divide-slate-100">{buildReportPreviewRows(selectedReport).map((row) => <tr key={row.recordId}><td className="p-3 font-mono text-slate-500">{row.recordId}</td><td className="p-3 font-medium text-slate-800">{row.entity}</td><td className="p-3"><span className={`rounded-full px-2 py-1 text-[10px] font-semibold ${row.result === 'Complete' ? 'bg-emerald-50 text-emerald-700' : 'bg-amber-50 text-amber-700'}`}>{row.result}</span></td><td className="p-3 text-slate-700">{row.measure}</td></tr>)}</tbody></table></div>
          </section>
          <div className="rounded-lg border border-indigo-100 bg-indigo-50 p-4 text-xs leading-relaxed text-indigo-900"><Eye className="mr-1 inline h-3.5 w-3.5" />Illustrative frontend report rows are shown here. Connect a live ERP data source to load the underlying production records.</div>
        </div>}
      </Modal>

      <Modal isOpen={scheduleOpen} onClose={() => setScheduleOpen(false)} title="Schedule report" size="sm" footer={<div className="flex justify-end gap-2"><Button variant="outline" onClick={() => setScheduleOpen(false)}>Cancel</Button><Button onClick={saveSchedule}><Calendar className="h-4 w-4" /> Save schedule</Button></div>}>
        <div className="space-y-4"><p className="text-sm text-slate-600">Schedule <strong>{selectedTemplate?.name}</strong> for recurring generation.</p><Select label="Frequency" value={scheduleFrequency} onChange={setScheduleFrequency} options={[{ value: 'Daily', label: 'Daily' }, { value: 'Weekly', label: 'Weekly' }, { value: 'Monthly', label: 'Monthly' }, { value: 'Quarterly', label: 'Quarterly' }]} /><p className="text-xs text-slate-400">Scheduled reports are recorded locally in this preview; no email or background job is created.</p></div>
      </Modal>

      {toast && <div role="status" className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-slate-900 px-4 py-3 text-sm text-white shadow-xl"><CheckCircle2 className="h-4 w-4 text-emerald-300" />{toast}<button onClick={() => setToast('')} aria-label="Dismiss notification"><X className="ml-2 h-3.5 w-3.5" /></button></div>}
    </div>
  );
}

export default AdministrativeControlReports;
