import React, { useMemo, useState } from 'react';
import { CheckCircle2, Download, Filter, History, LockKeyhole, Search, ShieldCheck } from 'lucide-react';
import { Badge } from '../../../components/ui/Badge';
import { Button } from '../../../components/ui/Button';
import { Card } from '../../../components/ui/Card';
import { Modal } from '../../../components/ui/Modal';

type AuditEvent = {
  id: string; requestId: string; title: string; module: string; branch: string; actor: string; actorRole: string;
  action: string; result: string; timestamp: string; ageDays: number; duration: string; workflow: string;
  comment: string; ip: string; channel: string; level: string;
};
const AUDIT_EVENTS: AuditEvent[] = [
  { id: 'AUD-89042', requestId: 'FC-2026-0754', title: 'Fee concession — Kavya Patel', module: 'Student Services', branch: 'Main Campus', actor: 'Ananya Desai', actorRole: 'Principal', action: 'Approved', result: 'Final approval', timestamp: '02 Oct 2026 · 10:42:18', ageDays: 0, duration: '1d 4h', workflow: 'Fee Concession Request v6', comment: 'Supporting evidence reviewed; approve 15% concession for current term.', ip: '10.24.8.16', channel: 'Web portal', level: 'Level 3 of 3' },
  { id: 'AUD-89041', requestId: 'PO-2026-2178', title: 'Purchase order — classroom furniture', module: 'Procurement', branch: 'North Branch', actor: 'Workflow Engine', actorRole: 'System', action: 'Escalated', result: 'SLA breach route', timestamp: '02 Oct 2026 · 10:28:03', ageDays: 0, duration: '12h 1m', workflow: 'Purchase Order — High Value v2', comment: 'SLA exceeded. Routed to Operations Director and priority raised to Critical.', ip: 'System event', channel: 'Automated rule', level: 'Escalation stage 2' },
  { id: 'AUD-89040', requestId: 'EX-2026-0392', title: 'Expense claim — conference travel', module: 'Finance', branch: 'Main Campus', actor: 'Rahul Mehta', actorRole: 'Finance Controller', action: 'Rejected', result: 'Returned for correction', timestamp: '02 Oct 2026 · 10:14:51', ageDays: 0, duration: '7h 30m', workflow: 'Expense Reimbursement v5', comment: 'Please attach the itemized receipt; current image does not show tax details.', ip: '10.24.8.32', channel: 'Web portal', level: 'Level 2 of 2' },
  { id: 'AUD-89039', requestId: 'LV-2026-336', title: 'Leave request — R. Shah', module: 'HR', branch: 'South Branch', actor: 'Neha Trivedi', actorRole: 'HR Manager', action: 'Delegated', result: 'Authority transfer', timestamp: '02 Oct 2026 · 09:57:26', ageDays: 0, duration: '—', workflow: 'Teaching Staff Leave v3', comment: 'Delegated to Kavita Rao while attending regional HR meeting.', ip: '10.24.9.11', channel: 'Web portal', level: 'Delegation record' },
  { id: 'AUD-89038', requestId: 'REQ-2026-1108', title: 'Classroom stationery request', module: 'Procurement', branch: 'Main Campus', actor: 'Workflow Engine', actorRole: 'System', action: 'Auto-approved', result: 'Policy threshold met', timestamp: '02 Oct 2026 · 09:43:09', ageDays: 0, duration: '2m', workflow: 'Purchase Requisition — Standard v4', comment: 'Amount below configured threshold and budget was confirmed.', ip: 'System event', channel: 'Automated rule', level: 'Auto-decision' },
  { id: 'AUD-89037', requestId: 'PAY-2026-0837', title: 'Supplier payment — Maple Books', module: 'Finance', branch: 'North Branch', actor: 'Rahul Mehta', actorRole: 'Finance Controller', action: 'Approved', result: 'Level approval', timestamp: '02 Oct 2026 · 09:25:14', ageDays: 0, duration: '5h 22m', workflow: 'Supplier Payment v4', comment: 'Invoice and purchase order match; tax details verified.', ip: '10.24.8.32', channel: 'Web portal', level: 'Level 2 of 3' },
  { id: 'AUD-89036', requestId: 'AD-2026-0139', title: 'Admission exception — mid-year entry', module: 'Admissions', branch: 'South Branch', actor: 'Pooja Shah', actorRole: 'Admissions Lead', action: 'Approved', result: 'Level approval', timestamp: '02 Oct 2026 · 08:56:10', ageDays: 0, duration: '13h 2m', workflow: 'Admission Exception v2', comment: 'Prior school transcript and seat availability confirmed.', ip: '10.24.9.19', channel: 'Mobile app', level: 'Level 1 of 2' },
  { id: 'AUD-89035', requestId: 'TR-2026-048', title: 'Transport vendor renewal', module: 'Transport', branch: 'North Branch', actor: 'Chirag Shah', actorRole: 'Transport Head', action: 'Put on hold', result: 'Additional review required', timestamp: '02 Oct 2026 · 08:21:55', ageDays: 0, duration: '1d 8h', workflow: 'Transport Contract Renewal v3', comment: 'Hold until updated vehicle fitness certificates are attached.', ip: '10.24.9.42', channel: 'Web portal', level: 'Level 2 of 3' },
  { id: 'AUD-89034', requestId: 'IT-2026-0233', title: 'Access request — new staff member', module: 'IT & Facilities', branch: 'Main Campus', actor: 'Sanjay Rao', actorRole: 'IT Manager', action: 'Approved', result: 'Final approval', timestamp: '02 Oct 2026 · 07:49:37', ageDays: 0, duration: '1h 54m', workflow: 'Staff System Access v2', comment: 'Role profile verified against the signed appointment.', ip: '10.24.8.22', channel: 'Web portal', level: 'Level 2 of 2' },
  { id: 'AUD-89033', requestId: 'FC-2026-0748', title: 'Fee concession — Dev Patel', module: 'Student Services', branch: 'South Branch', actor: 'Workflow Engine', actorRole: 'System', action: 'Reminder sent', result: 'SLA reminder', timestamp: '02 Oct 2026 · 07:36:01', ageDays: 0, duration: '—', workflow: 'Fee Concession Request v6', comment: 'Reminder sent to Admissions Committee at 75% of the assigned SLA.', ip: 'System event', channel: 'Email + in-app', level: 'Level 3 of 3' },
  { id: 'AUD-88996', requestId: 'PO-2026-2147', title: 'Library book procurement', module: 'Procurement', branch: 'Main Campus', actor: 'Vikram Joshi', actorRole: 'Operations Director', action: 'Approved', result: 'Final approval', timestamp: '01 Oct 2026 · 16:48:02', ageDays: 1, duration: '2d 7h', workflow: 'Purchase Order — High Value v2', comment: 'Approve against the confirmed library budget.', ip: '10.24.8.16', channel: 'Web portal', level: 'Level 3 of 3' },
  { id: 'AUD-88995', requestId: 'HR-2026-0898', title: 'New position requisition', module: 'HR', branch: 'North Branch', actor: 'Amit Patel', actorRole: 'Vice Principal', action: 'Returned', result: 'Information requested', timestamp: '01 Oct 2026 · 15:20:16', ageDays: 1, duration: '5h 48m', workflow: 'Staff Recruitment Request v4', comment: 'Please attach the revised timetable showing the teaching requirement.', ip: '10.24.8.20', channel: 'Web portal', level: 'Level 2 of 3' }
];
const MODULES = ['Admissions', 'Finance', 'HR', 'IT & Facilities', 'Procurement', 'Student Services', 'Transport'];
const ACTIONS = ['Approved', 'Rejected', 'Escalated', 'Delegated', 'Auto-approved', 'Put on hold', 'Reminder sent', 'Returned'];
const actionVariant = (action: string): 'success' | 'danger' | 'warning' | 'info' => action === 'Approved' || action === 'Auto-approved' ? 'success' : action === 'Rejected' ? 'danger' : action === 'Escalated' ? 'warning' : 'info';

export function ApprovalHistoryAudit() {
  const [query, setQuery] = useState('');
  const [moduleFilter, setModuleFilter] = useState('All modules');
  const [actionFilter, setActionFilter] = useState('All actions');
  const [period, setPeriod] = useState('Last 7 days');
  const [selectedEvent, setSelectedEvent] = useState<AuditEvent | null>(null);
  const [page, setPage] = useState(1);
  const pageSize = 8;

  const filteredEvents = useMemo(() => AUDIT_EVENTS.filter((event) => {
    const searchable = `${event.id} ${event.requestId} ${event.title} ${event.actor} ${event.actorRole} ${event.comment}`.toLowerCase();
    const inPeriod = period === 'Last 24 hours' ? event.ageDays === 0 : period === 'Last 7 days' ? event.ageDays <= 7 : true;
    return searchable.includes(query.toLowerCase()) && (moduleFilter === 'All modules' || event.module === moduleFilter) && (actionFilter === 'All actions' || event.action === actionFilter) && inPeriod;
  }), [query, moduleFilter, actionFilter, period]);
  const pageCount = Math.max(1, Math.ceil(filteredEvents.length / pageSize));
  const pageEvents = filteredEvents.slice((page - 1) * pageSize, page * pageSize);

  const exportAudit = () => {
    const rows = [['Log ID', 'Request ID', 'Title', 'Module', 'Branch', 'Actor', 'Role', 'Action', 'Result', 'Timestamp', 'Workflow', 'Comment'], ...filteredEvents.map((event) => [event.id, event.requestId, event.title, event.module, event.branch, event.actor, event.actorRole, event.action, event.result, event.timestamp, event.workflow, event.comment])];
    const csv = rows.map((row) => row.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\n');
    const blob = new Blob([csv], { type: 'text/csv;charset=utf-8' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'approval-history-audit.csv'; link.click(); URL.revokeObjectURL(link.href);
  };
  const clearFilters = () => { setQuery(''); setModuleFilter('All modules'); setActionFilter('All actions'); setPeriod('Last 7 days'); setPage(1); };

  return (
    <div className="min-h-full space-y-5 bg-slate-50 p-4 md:p-6">
      <header className="flex flex-col justify-between gap-4 lg:flex-row lg:items-end"><div><div className="mb-1 text-xs text-slate-500">Administration / Central Approval Desk / <span className="text-blue-700">Approval History & Audit</span></div><div className="flex flex-wrap items-center gap-3"><h1 className="text-2xl font-bold text-slate-900">Approval History & Audit</h1><Badge variant="outline"><LockKeyhole className="mr-1 h-3 w-3" /> Immutable log</Badge></div><p className="mt-1 text-sm text-slate-500">Search a timestamped record of approval decisions, workflow transitions, delegations, and automated rules.</p></div><div className="flex flex-wrap gap-2"><Button variant="outline" size="sm" onClick={exportAudit}><Download className="h-4 w-4" /> Export filtered log</Button><Button variant="outline" size="sm" onClick={() => window.print()}><History className="h-4 w-4" /> Print</Button></div></header>

      <section className="grid grid-cols-2 gap-3 xl:grid-cols-4">{[
        { label: 'Audit events', value: '18,492', note: 'All time · group-wide', icon: History, tone: 'bg-blue-50 text-blue-700' },
        { label: 'Decisions today', value: '186', note: 'Approval and rejection events', icon: CheckCircle2, tone: 'bg-emerald-50 text-emerald-700' },
        { label: 'Automated actions', value: '42', note: 'Rules, reminders, escalations', icon: History, tone: 'bg-violet-50 text-violet-700' },
        { label: 'Audit integrity', value: 'Verified', note: 'Append-only event sequence', icon: ShieldCheck, tone: 'bg-teal-50 text-teal-700' }
      ].map((metric) => { const Icon = metric.icon; return <Card key={metric.label} className="p-4"><div className="flex items-start justify-between"><div><p className="text-xs text-slate-500">{metric.label}</p><p className="mt-1 text-2xl font-bold text-slate-900">{metric.value}</p><p className="mt-1 text-[11px] text-slate-400">{metric.note}</p></div><span className={`rounded-lg p-2 ${metric.tone}`}><Icon className="h-4 w-4" /></span></div></Card>; })}</section>

      <Card className="p-4"><div className="grid grid-cols-1 gap-3 md:grid-cols-[minmax(220px,1.5fr)_1fr_1fr_1fr_auto]"><div className="relative"><Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-slate-400" /><input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1); }} placeholder="Search request, user, reference, comment..." className="w-full rounded-lg border border-slate-200 py-2.5 pl-9 pr-3 text-sm outline-none focus:ring-2 focus:ring-blue-100" /></div><select value={moduleFilter} onChange={(event) => { setModuleFilter(event.target.value); setPage(1); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option>All modules</option>{MODULES.map((module) => <option key={module}>{module}</option>)}</select><select value={actionFilter} onChange={(event) => { setActionFilter(event.target.value); setPage(1); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option>All actions</option>{ACTIONS.map((action) => <option key={action}>{action}</option>)}</select><select value={period} onChange={(event) => { setPeriod(event.target.value); setPage(1); }} className="rounded-lg border border-slate-200 bg-white px-3 py-2.5 text-sm"><option>Last 24 hours</option><option>Last 7 days</option><option>Last 30 days</option><option>All time</option></select><Button variant="ghost" size="sm" onClick={clearFilters}><Filter className="h-4 w-4" /> Reset</Button></div></Card>

      <Card className="overflow-hidden p-0"><div className="flex flex-wrap items-center justify-between gap-2 border-b border-slate-200 px-5 py-4"><div><h2 className="font-semibold text-slate-900">Audit event log</h2><p className="mt-1 text-xs text-slate-500">Showing {filteredEvents.length} events · newest first · records cannot be edited or deleted</p></div><Badge variant="success"><span className="mr-1 h-1.5 w-1.5 rounded-full bg-emerald-500" /> Integrity verified</Badge></div><div className="overflow-x-auto"><table className="min-w-[1120px] w-full text-left text-xs"><thead className="bg-slate-50 uppercase tracking-wider text-slate-500"><tr><th className="px-4 py-3">Event / request</th><th className="px-3 py-3">Action / result</th><th className="px-3 py-3">Actor</th><th className="px-3 py-3">Module / branch</th><th className="px-3 py-3">Timestamp</th><th className="px-3 py-3">Workflow</th><th className="px-4 py-3 text-right">Detail</th></tr></thead><tbody className="divide-y divide-slate-100">{pageEvents.map((event) => <tr key={event.id} className="hover:bg-slate-50"><td className="px-4 py-3"><span className="block font-semibold text-slate-800">{event.title}</span><span className="mt-1 block font-mono text-[10px] text-slate-400">{event.id} · {event.requestId}</span></td><td className="px-3 py-3"><Badge variant={actionVariant(event.action)}>{event.action}</Badge><span className="mt-1 block text-slate-400">{event.result}</span></td><td className="px-3 py-3"><span className="block font-medium text-slate-700">{event.actor}</span><span className="mt-1 block text-slate-400">{event.actorRole}</span></td><td className="px-3 py-3"><span className="block text-slate-700">{event.module}</span><span className="mt-1 block text-slate-400">{event.branch}</span></td><td className="px-3 py-3 text-slate-600">{event.timestamp}</td><td className="max-w-[180px] px-3 py-3 text-slate-500">{event.workflow}</td><td className="px-4 py-3 text-right"><Button variant="ghost" size="xs" onClick={() => setSelectedEvent(event)}>View audit</Button></td></tr>)}{!pageEvents.length && <tr><td colSpan={7} className="px-4 py-12 text-center text-slate-500">No audit events match these filters.</td></tr>}</tbody></table></div><div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-200 px-5 py-3 text-xs text-slate-500"><span>Audit records are append-only and preserve actor, timestamp, channel, and source.</span><div className="flex items-center gap-2"><button disabled={page <= 1} onClick={() => setPage((value) => Math.max(1, value - 1))} className="rounded border border-slate-200 px-2 py-1 disabled:opacity-40">Previous</button><span>Page {page} of {pageCount}</span><button disabled={page >= pageCount} onClick={() => setPage((value) => Math.min(pageCount, value + 1))} className="rounded border border-slate-200 px-2 py-1 disabled:opacity-40">Next</button></div></div></Card>

      <div className="rounded-lg border border-blue-100 bg-blue-50 px-4 py-3 text-xs leading-relaxed text-blue-800"><ShieldCheck className="mr-1 inline h-3.5 w-3.5" />Audit entries shown here are representative frontend sample data. The log viewer is read-only; retention, signatures, and tamper evidence are provided by the connected audit service.</div>

      <Modal isOpen={Boolean(selectedEvent)} onClose={() => setSelectedEvent(null)} title="Audit event details" size="lg" footer={<div className="flex justify-end"><Button onClick={() => setSelectedEvent(null)}>Close</Button></div>}>{selectedEvent && <div className="space-y-4"><div className="flex flex-wrap gap-2"><Badge variant={actionVariant(selectedEvent.action)}>{selectedEvent.action}</Badge><Badge variant="outline">{selectedEvent.id}</Badge><Badge variant="info">{selectedEvent.level}</Badge></div><div><h3 className="text-lg font-semibold text-slate-900">{selectedEvent.title}</h3><p className="mt-1 text-sm text-slate-500">{selectedEvent.requestId} · {selectedEvent.module} · {selectedEvent.branch}</p></div><div className="grid grid-cols-2 gap-3 rounded-xl bg-slate-50 p-4 text-sm md:grid-cols-3"><div><p className="text-xs text-slate-400">Actor</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.actor}</p><p className="text-xs text-slate-400">{selectedEvent.actorRole}</p></div><div><p className="text-xs text-slate-400">Timestamp</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.timestamp}</p></div><div><p className="text-xs text-slate-400">Time in workflow</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.duration}</p></div><div><p className="text-xs text-slate-400">Channel</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.channel}</p></div><div><p className="text-xs text-slate-400">Source address</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.ip}</p></div><div><p className="text-xs text-slate-400">Workflow version</p><p className="mt-1 font-medium text-slate-800">{selectedEvent.workflow}</p></div></div><div className="rounded-lg border border-slate-200 p-4"><p className="text-xs font-semibold uppercase tracking-wider text-slate-400">Recorded comment / reason</p><p className="mt-2 text-sm leading-relaxed text-slate-700">{selectedEvent.comment}</p></div><div className="flex items-start gap-2 rounded-lg border border-emerald-100 bg-emerald-50 p-3 text-xs text-emerald-800"><LockKeyhole className="mt-0.5 h-4 w-4 shrink-0" />Event is read-only and retained as part of the audit sequence.</div><div className="flex items-center justify-between border-t border-slate-100 pt-3 text-xs text-slate-400"><span>Integrity chain verified</span><span>System event hash · {selectedEvent.id.slice(-6)}-7A21</span></div></div>}</Modal>
    </div>
  );
}

export default ApprovalHistoryAudit;
